import type { Copy, EvidenceCard, Locale, LocalizedList, LocalizedText, NoiseType } from './types';

export const copy: Record<Locale, Copy> = {
  ja: {
    appName: 'Noise Maker',
    appTagline: 'シンプルに、静かに、聞きたい音だけ。',
    install: 'ホーム画面に追加',
    installHint: 'ホーム画面に追加すると、起動が速くなります。',
    play: '再生',
    stop: '停止',
    addToHomeScreen: 'ホーム画面に追加',
    evidenceTitle: '説明と論文',
    platformTitle: 'PWA と端末差分',
    simpleExplanationTitle: '短い説明',
    volumeLabel: '音量',
    timerLabel: 'タイマー',
    timerOff: 'なし',
    installInfo: 'インストール情報を表示',
    addHome: 'ホーム画面に追加',
    aboutBackground: 'バックグラウンドでの動作について',
    noiseType: 'ノイズタイプ',
    noisePapers: 'ノイズの論文リンクを表示',
    noiseReferences: 'ノイズに関する参考論文',
    binauralOn: 'バイノーラルビート ON',
    binauralHelp: 'バイノーラルビートの説明を表示',
    binauralDesc: '左右の耳に少し異なる周波数を流し、差分周波数を体感しやすくする機能です。',
    baseFreq: 'ベース周波数',
    currentBand: '現在の差分周波数の目安',
    footerNote: '医療効果を保証するものではありません。用途に合わせて慎重に使ってください。',
    minute: '分',
    second: '秒'
  },
  en: {
    appName: 'Noise Maker',
    appTagline: 'Simple noise and binaural beats, tuned for phones.',
    install: 'Add to Home Screen',
    installHint: 'Adding to the home screen makes launch faster.',
    play: 'Play',
    stop: 'Stop',
    addToHomeScreen: 'Add to Home Screen',
    evidenceTitle: 'Explanation and papers',
    platformTitle: 'PWA and platform differences',
    simpleExplanationTitle: 'Plain explanation',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Off',
    installInfo: 'Show installation info',
    addHome: 'Add to home screen',
    aboutBackground: 'About background playback',
    noiseType: 'Noise type',
    noisePapers: 'Show noise papers',
    noiseReferences: 'References for noise studies',
    binauralOn: 'Binaural beats on',
    binauralHelp: 'Show binaural beat help',
    binauralDesc: 'This sends slightly different tones to each ear so the beat difference can be perceived more clearly.',
    baseFreq: 'Base frequency',
    currentBand: 'Current beat band',
    footerNote: 'No medical claims are made. Use it cautiously and fit it to your context.',
    minute: 'm',
    second: 's'
  },
  'zh-Hans': {
    appName: 'Noise Maker',
    appTagline: '简洁、安静，只播放你想听的声音。',
    install: '添加到主屏幕',
    installHint: '添加到主屏幕后，启动会更快。',
    play: '播放',
    stop: '停止',
    addToHomeScreen: '添加到主屏幕',
    evidenceTitle: '说明与论文',
    platformTitle: 'PWA 与设备差异',
    simpleExplanationTitle: '简短说明',
    volumeLabel: '音量',
    timerLabel: '计时器',
    timerOff: '关闭',
    installInfo: '显示安装信息',
    addHome: '添加到主屏幕',
    aboutBackground: '关于后台播放',
    noiseType: '噪音类型',
    noisePapers: '显示噪音论文',
    noiseReferences: '噪音研究参考',
    binauralOn: '开启双耳节拍',
    binauralHelp: '显示双耳节拍帮助',
    binauralDesc: '向每只耳朵发送略有不同的音调，以便更清晰地感知节拍差异。',
    baseFreq: '基准频率',
    currentBand: '当前节拍频带',
    footerNote: '不作医疗声明。请谨慎使用并适应您的环境。',
    minute: '分',
    second: '秒'
  },
  es: {
    appName: 'Noise Maker',
    appTagline: 'Simple, tranquilo, solo el sonido que quieres.',
    install: 'Agregar a pantalla de inicio',
    installHint: 'Agregarla a la pantalla de inicio acelera el inicio.',
    play: 'Reproducir',
    stop: 'Detener',
    addToHomeScreen: 'Agregar a pantalla de inicio',
    evidenceTitle: 'Explicación y estudios',
    platformTitle: 'PWA y diferencias de plataforma',
    simpleExplanationTitle: 'Explicación breve',
    volumeLabel: 'Volumen',
    timerLabel: 'Temporizador',
    timerOff: 'Desactivado',
    installInfo: 'Mostrar info de instalación',
    addHome: 'Agregar a la pantalla de inicio',
    aboutBackground: 'Sobre reproducción en segundo plano',
    noiseType: 'Tipo de ruido',
    noisePapers: 'Mostrar estudios de ruido',
    noiseReferences: 'Referencias para estudios de ruido',
    binauralOn: 'Pulsos binaurales activados',
    binauralHelp: 'Mostrar ayuda de pulsos binaurales',
    binauralDesc: 'Envía tonos ligeramente diferentes a cada oído para que la diferencia de pulso se perciba más claramente.',
    baseFreq: 'Frecuencia base',
    currentBand: 'Banda de pulso actual',
    footerNote: 'No se realizan afirmaciones médicas. Úselo con precaución y adáptelo a su contexto.',
    minute: 'm',
    second: 's'
  },
  hi: {
    appName: 'Noise Maker',
    appTagline: 'सरल, शांत, बस वही ध्वनि जो आप सुनना चाहें।',
    install: 'होम स्क्रीन पर जोड़ें',
    installHint: 'होम स्क्रीन पर जोड़ने से ऐप जल्दी खुलता है।',
    play: 'चलाएँ',
    stop: 'रोकें',
    addToHomeScreen: 'होम स्क्रीन पर जोड़ें',
    evidenceTitle: 'व्याख्या और शोध पत्र',
    platformTitle: 'PWA और प्लेटफ़ॉर्म अंतर',
    simpleExplanationTitle: 'संक्षिप्त व्याख्या',
    volumeLabel: 'आवाज़',
    timerLabel: 'टाइमर',
    timerOff: 'बंद',
    installInfo: 'इंस्टॉलेशन जानकारी दिखाएं',
    addHome: 'होम स्क्रीन पर जोड़ें',
    aboutBackground: 'बैकग्राउंड प्लेबैक के बारे में',
    noiseType: 'शोर का प्रकार',
    noisePapers: 'शोर शोध पत्र दिखाएं',
    noiseReferences: 'शोर अध्ययन के संदर्भ',
    binauralOn: 'बाइनोरल बीट्स चालू',
    binauralHelp: 'बाइनोरल बीट सहायता दिखाएं',
    binauralDesc: 'प्रत्येक कान में थोड़े अलग टोन भेजता है ताकि बीट अंतर को अधिक स्पष्ट रूप से समझा जा सके।',
    baseFreq: 'आधार आवृत्ति',
    currentBand: 'वर्तमान बीट बैंड',
    footerNote: 'कोई चिकित्सा दावा नहीं किया गया है। इसका सावधानीपूर्वक उपयोग करें और अपने संदर्भ के अनुसार ढालें।',
    minute: 'म',
    second: 'से'
  },
  bn: {
    appName: 'Noise Maker',
    appTagline: 'সহজ, শান্ত, শুধু আপনার পছন্দের শব্দ।',
    install: 'হোম স্ক্রিনে যোগ করুন',
    installHint: 'হোম স্ক্রিনে যোগ করলে দ্রুত চালু হবে।',
    play: 'চালু',
    stop: 'বন্ধ',
    addToHomeScreen: 'হোম স্ক্রিনে যোগ করুন',
    evidenceTitle: 'ব্যাখ্যা ও গবেষণা',
    platformTitle: 'PWA ও প্ল্যাটফর্ম পার্থক্য',
    simpleExplanationTitle: 'সংক্ষিপ্ত ব্যাখ্যা',
    volumeLabel: 'ভলিউম',
    timerLabel: 'টাইমার',
    timerOff: 'বন্ধ',
    installInfo: 'ইনস্টলেশন তথ্য দেখান',
    addHome: 'হোম স্ক্রিনে যোগ করুন',
    aboutBackground: 'ব্যাকগ্রাউন্ড প্লেব্যাক সম্পর্কে',
    noiseType: 'শব্দের ধরণ',
    noisePapers: 'শব্দ গবেষণা পত্র দেখান',
    noiseReferences: 'শব্দ অধ্যয়নের রেফারেন্স',
    binauralOn: 'বাইনরাল বিটস চালু',
    binauralHelp: 'বাইনরাল বিট সহায়তা দেখান',
    binauralDesc: 'প্রতিটি কানে সামান্য ভিন্ন সুর পাঠায় যাতে বিট পার্থক্য আরও স্পষ্টভাবে বোঝা যায়।',
    baseFreq: 'বেস ফ্রিকোয়েন্সি',
    currentBand: 'বর্তমান বিট ব্যান্ড',
    footerNote: 'কোন চিকিৎসা দাবি করা হয় না। এটি সাবধানতার সাথে ব্যবহার করুন এবং আপনার প্রেক্ষাপটের সাথে খাপ খাইয়ে নিন।',
    minute: 'মি',
    second: 'সে'
  },
  pt: {
    appName: 'Noise Maker',
    appTagline: 'Simples e calmo, apenas o som que voce quer ouvir.',
    install: 'Adicionar a tela inicial',
    installHint: 'Adicionar a tela inicial deixa a abertura mais rapida.',
    play: 'Reproduzir',
    stop: 'Parar',
    addToHomeScreen: 'Adicionar a tela inicial',
    evidenceTitle: 'Explicacao e artigos',
    platformTitle: 'PWA e diferencas de plataforma',
    simpleExplanationTitle: 'Explicacao curta',
    volumeLabel: 'Volume',
    timerLabel: 'Temporizador',
    timerOff: 'Desligado',
    installInfo: 'Mostrar info de instalacao',
    addHome: 'Adicionar a tela inicial',
    aboutBackground: 'Sobre reproducao em segundo plano',
    noiseType: 'Tipo de ruido',
    noisePapers: 'Mostrar artigos de ruido',
    noiseReferences: 'Referencias para estudos de ruido',
    binauralOn: 'Batidas binaurais ligadas',
    binauralHelp: 'Mostrar ajuda de batidas binaurais',
    binauralDesc: 'Envia tons ligeiramente diferentes para cada ouvido para que a diferenca de batida seja percebida mais claramente.',
    baseFreq: 'Frequencia base',
    currentBand: 'Banda de batida atual',
    footerNote: 'Nenhuma alegacao medica e feita. Use com cautela e adapte ao seu contexto.',
    minute: 'm',
    second: 's'
  },
  ru: {
    appName: 'Noise Maker',
    appTagline: 'Просто, спокойно, только нужный вам звук.',
    install: 'Добавить на главный экран',
    installHint: 'Добавление на главный экран ускоряет запуск.',
    play: 'Воспроизвести',
    stop: 'Остановить',
    addToHomeScreen: 'Добавить на главный экран',
    evidenceTitle: 'Объяснение и статьи',
    platformTitle: 'PWA и различия платформ',
    simpleExplanationTitle: 'Краткое объяснение',
    volumeLabel: 'Громкость',
    timerLabel: 'Таймер',
    timerOff: 'Выкл',
    installInfo: 'Показать инфо об установке',
    addHome: 'Добавить на главный экран',
    aboutBackground: 'О фоновом воспроизведении',
    noiseType: 'Тип шума',
    noisePapers: 'Показать статьи о шуме',
    noiseReferences: 'Ссылки на исследования шума',
    binauralOn: 'Бинауральные ритмы вкл',
    binauralHelp: 'Показать справку по ритмам',
    binauralDesc: 'Подает слегка разные тона в каждое ухо, чтобы разница ритмов воспринималась четче.',
    baseFreq: 'Базовая частота',
    currentBand: 'Текущий диапазон ритма',
    footerNote: 'Медицинские заявления не делаются. Используйте с осторожностью и адаптируйте под себя.',
    minute: 'мин',
    second: 'сек'
  },
  yue: {
    appName: 'Noise Maker',
    appTagline: '簡單、寧靜，只播你想聽嘅聲音。',
    install: '加入主畫面',
    installHint: '加入主畫面之後，啟動會更快。',
    play: '播放',
    stop: '停止',
    addToHomeScreen: '加入主畫面',
    evidenceTitle: '說明同論文',
    platformTitle: 'PWA 同平台差異',
    simpleExplanationTitle: '簡短說明',
    volumeLabel: '音量',
    timerLabel: '計時器',
    timerOff: '關閉',
    installInfo: '顯示安裝資訊',
    addHome: '加入主畫面',
    aboutBackground: '關於背景播放',
    noiseType: '噪音類型',
    noisePapers: '顯示噪音論文',
    noiseReferences: '噪音研究參考',
    binauralOn: '開啟雙耳節拍',
    binauralHelp: '顯示雙耳節拍說明',
    binauralDesc: '向每隻耳仔發送略有不同嘅音調，以便更清晰地感知節拍差異。',
    baseFreq: '基準頻率',
    currentBand: '當前節拍頻帶',
    footerNote: '唔作醫療聲明。請謹慎使用並適應你嘅環境。',
    minute: '分',
    second: '秒'
  },
  vi: {
    appName: 'Noise Maker',
    appTagline: 'Don gian, yen tinh, chi phat am thanh ban muon nghe.',
    install: 'Them vao man hinh chinh',
    installHint: 'Them vao man hinh chinh giup mo nhanh hon.',
    play: 'Phat',
    stop: 'Dung',
    addToHomeScreen: 'Them vao man hinh chinh',
    evidenceTitle: 'Giai thich va bai bao',
    platformTitle: 'PWA va khac biet nen tang',
    simpleExplanationTitle: 'Giai thich ngan',
    volumeLabel: 'Am luong',
    timerLabel: 'Hen gio',
    timerOff: 'Tat',
    installInfo: 'Hien thi thong tin cai dat',
    addHome: 'Them vao man hinh chinh',
    aboutBackground: 'Ve phat trong nen',
    noiseType: 'Loai tieng on',
    noisePapers: 'Hien thi bai bao ve tieng on',
    noiseReferences: 'Tai lieu tham khao tieng on',
    binauralOn: 'Bat nhip binaural',
    binauralHelp: 'Hien tro giup nhip binaural',
    binauralDesc: 'Gui cac am thanh hoi khac nhau den moi tai de co the cam nhan su khac biet nhip ro rang hon.',
    baseFreq: 'Tan so co ban',
    currentBand: 'Bang nhip hien tai',
    footerNote: 'Khong co tuyen bo y te nao duoc dua ra. Su dung than trong va phu hop voi boi canh cua ban.',
    minute: 'p',
    second: 'g'
  },
  mr: {
    appName: 'Noise Maker',
    appTagline: 'सोपे, शांत, फक्त तुम्हाला हवे तेच आवाज.',
    install: 'होम स्क्रीनवर जोडा',
    installHint: 'होम स्क्रीनवर जोडल्यास अॅप लवकर उघडते.',
    play: 'प्ले',
    stop: 'थांबवा',
    addToHomeScreen: 'होम स्क्रीनवर जोडा',
    evidenceTitle: 'स्पष्टीकरण आणि संदर्भ',
    platformTitle: 'PWA आणि प्लॅटफॉर्म फरक',
    simpleExplanationTitle: 'संक्षिप्त स्पष्टीकरण',
    volumeLabel: 'आवाज',
    timerLabel: 'टायमर',
    timerOff: 'बंद',
    installInfo: 'इन्स्टॉलेशन माहिती दाखवा',
    addHome: 'होम स्क्रीनवर जोडा',
    aboutBackground: 'बॅकग्राउंड प्लेबॅकबद्दल',
    noiseType: 'आवाजाचा प्रकार',
    noisePapers: 'आवाज शोधनिबंध दाखवा',
    noiseReferences: 'आवाज अभ्यासाचे संदर्भ',
    binauralOn: 'बाइनॉरॅरल बीट्स चालू',
    binauralHelp: 'बाइनॉरॅरल बीट मदत दाखवा',
    binauralDesc: 'प्रत्येक कानात थोडे वेगळे टोन पाठवते जेणेकरून बीटमधील फरक अधिक स्पष्टपणे समजू शकेल.',
    baseFreq: 'बेस फ्रिक्वेन्सी',
    currentBand: 'सध्याचा बीट बँड',
    footerNote: 'कोणताही वैद्यकीय दावा केला जात नाही. सावधगिरीने वापरा आणि तुमच्या संदर्भानुसार वापरा.',
    minute: 'मि',
    second: 'से'
  },
  te: {
    appName: 'Noise Maker',
    appTagline: 'సరళంగా, ప్రశాంతంగా, మీకు కావలసిన శబ్దమే.',
    install: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    installHint: 'హోమ్ స్క్రీన్‌కు చేర్చితే యాప్ త్వరగా తెరుచుకుంటుంది.',
    play: 'ప్లే',
    stop: 'ఆపు',
    addToHomeScreen: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    evidenceTitle: 'వివరణ మరియు పత్రాలు',
    platformTitle: 'PWA మరియు ప్లాట్‌ఫార్మ్ తేడాలు',
    simpleExplanationTitle: 'సంక్షిప్త వివరణ',
    volumeLabel: 'వాల్యూం',
    timerLabel: 'టైమర్',
    timerOff: 'ఆఫ్',
    installInfo: 'ఇన్‌స్టాలేషన్ సమాచారం చూపించు',
    addHome: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    aboutBackground: 'బ్యాక్‌గ్రౌండ్ ప్లేబ్యాక్ గురించి',
    noiseType: 'శబ్దం రకం',
    noisePapers: 'శబ్దం పత్రాలు చూపించు',
    noiseReferences: 'శబ్ద అధ్యయన సూచనలు',
    binauralOn: 'బైనరల్ బీట్స్ ఆన్',
    binauralHelp: 'బైనరల్ బీట్ సహాయం చూపించు',
    binauralDesc: 'ప్రతి చెవికి కొద్దిగా భిన్నమైన టోన్లను పంపుతుంది, తద్వారా బీట్ తేడా మరింత స్పష్టంగా కనిపిస్తుంది.',
    baseFreq: 'బేస్ ఫ్రీక్వెన్సీ',
    currentBand: 'ప్రస్తుత బీట్ బ్యాండ్',
    footerNote: 'వైద్యపరమైన క్లెయిమ్‌లు ఏవీ చేయబడలేదు. జాగ్రత్తగా ఉపయోగించండి మరియు మీ సందర్భానికి తగినట్లుగా అమర్చుకోండి.',
    minute: 'ని',
    second: 'సె'
  },
  tr: {
    appName: 'Noise Maker',
    appTagline: 'Basit, sakin, sadece duymak istedigin ses.',
    install: 'Ana ekrana ekle',
    installHint: 'Ana ekrana eklemek daha hizli acilis saglar.',
    play: 'Oynat',
    stop: 'Durdur',
    addToHomeScreen: 'Ana ekrana ekle',
    evidenceTitle: 'Aciklama ve makaleler',
    platformTitle: 'PWA ve platform farklari',
    simpleExplanationTitle: 'Kisa aciklama',
    volumeLabel: 'Ses',
    timerLabel: 'Zamanlayici',
    timerOff: 'Kapali',
    installInfo: 'Kurulum bilgisini goster',
    addHome: 'Ana ekrana ekle',
    aboutBackground: 'Arka plan oynatma hakkinda',
    noiseType: 'Gurultu tipi',
    noisePapers: 'Gurultu makalelerini goster',
    noiseReferences: 'Gurultu calismalari referanslari',
    binauralOn: 'Binaural vuruslar acik',
    binauralHelp: 'Binaural vurus yardimini goster',
    binauralDesc: 'Vurus farkinin daha net algilanabilmesi icin her kulaga biraz farkli tonlar gonderir.',
    baseFreq: 'Temel frekans',
    currentBand: 'Guncel vurus bandi',
    footerNote: 'Tibbi bir iddiada bulunulmamaktadir. Dikkatli kullanin ve baglaminiza gore uyarlayin.',
    minute: 'dk',
    second: 'sn'
  },
  ko: {
    appName: 'Noise Maker',
    appTagline: '간단하고 조용하게, 원하는 소리만.',
    install: '홈 화면에 추가',
    installHint: '홈 화면에 추가하면 더 빠르게 실행됩니다.',
    play: '재생',
    stop: '정지',
    addToHomeScreen: '홈 화면에 추가',
    evidenceTitle: '설명과 논문',
    platformTitle: 'PWA 및 플랫폼 차이',
    simpleExplanationTitle: '짧은 설명',
    volumeLabel: '볼륨',
    timerLabel: '타이머',
    timerOff: '끔',
    installInfo: '설치 정보 표시',
    addHome: '홈 화면에 추가',
    aboutBackground: '백그라운드 재생에 대하여',
    noiseType: '노이즈 유형',
    noisePapers: '노이즈 논문 표시',
    noiseReferences: '노이즈 연구 참고 문서',
    binauralOn: '바이노럴 비트 켜짐',
    binauralHelp: '바이노럴 비트 도움말 표시',
    binauralDesc: '양쪽 귀에 약간 다른 주파수를 흘려 차이 주파수를 더 명확하게 느낄 수 있게 하는 기능입니다.',
    baseFreq: '베이스 주파수',
    currentBand: '현재 비트 밴드',
    footerNote: '의료적 효과를 보장하지 않습니다. 용도에 맞게 주의해서 사용하십시오.',
    minute: '분',
    second: '초'
  },
  pa: {
    appName: 'Noise Maker',
    appTagline: 'ਸੌਖਾ, ਸ਼ਾਂਤ, ਸਿਰਫ ਉਹੀ ਆਵਾਜ਼ ਜੋ ਤੁਸੀਂ ਸੁਣਨਾ ਚਾਹੋ।',
    install: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    installHint: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜਨ ਨਾਲ ਐਪ ਜਲਦੀ ਖੁਲਦਾ ਹੈ।',
    play: 'ਚਲਾਓ',
    stop: 'ਰੋਕੋ',
    addToHomeScreen: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    evidenceTitle: 'ਵਿਆਖਿਆ ਅਤੇ ਲੇਖ',
    platformTitle: 'PWA ਅਤੇ ਪਲੇਟਫਾਰਮ ਅੰਤਰ',
    simpleExplanationTitle: 'ਛੋਟੀ ਵਿਆਖਿਆ',
    volumeLabel: 'ਆਵਾਜ਼',
    timerLabel: 'ਟਾਈਮਰ',
    timerOff: 'ਬੰਦ',
    installInfo: 'ਇੰਸਟਾਲੇਸ਼ਨ ਜਾਣਕਾਰੀ ਦਿਖਾਓ',
    addHome: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    aboutBackground: 'ਬੈਕਗ੍ਰਾਉਂਡ ਪਲੇਬੈਕ ਬਾਰੇ',
    noiseType: 'ਸ਼ੋਰ ਦੀ ਕਿਸਮ',
    noisePapers: 'ਸ਼ੋਰ ਲੇਖ ਦਿਖਾਓ',
    noiseReferences: 'ਸ਼ੋਰ ਅਧਿਐਨ ਦੇ ਹਵਾਲੇ',
    binauralOn: 'ਬਾਇਨੋਰਲ ਬੀਟਸ ਚਾਲੂ',
    binauralHelp: 'ਬਾਇਨੋਰਲ ਬੀਟ ਸਹਾਇਤਾ ਦਿਖਾਓ',
    binauralDesc: 'ਹਰੇਕ ਕੰਨ ਵਿੱਚ ਥੋੜੇ ਵੱਖਰੇ ਟੋਨ ਭੇਜਦਾ ਹੈ ਤਾਂ ਜੋ ਬੀਟ ਦੇ ਅੰਤਰ ਨੂੰ ਹੋਰ ਸਪਸ਼ਟ ਰੂਪ ਵਿੱਚ ਸਮਝਿਆ ਜਾ ਸਕੇ।',
    baseFreq: 'ਬੇਸ ਫ੍ਰੀਕੁਐਂਸੀ',
    currentBand: 'ਮੌਜੂਦਾ ਬੀਟ ਬੈਂਡ',
    footerNote: 'ਕੋਈ ਡਾਕਟਰੀ ਦਾਅਵਾ ਨਹੀਂ ਕੀਤਾ ਗਿਆ ਹੈ। ਇਸਦੀ ਸਾਵਧਾਨੀ ਨਾਲ ਵਰਤੋਂ ਕਰੋ ਅਤੇ ਆਪਣੇ ਸੰਦਰਭ ਅਨੁਸਾਰ ਢਾਲੋ।',
    minute: 'ਮਿੰਟ',
    second: 'ਸਕਿੰਟ'
  },
  ta: {
    appName: 'Noise Maker',
    appTagline: 'எளிதாக, அமைதியாக, உங்களுக்கு வேண்டிய ஒலி மட்டும்.',
    install: 'முதற்பக்கத்தில் சேர்க்க',
    installHint: 'முதற்பக்கத்தில் சேர்த்தால் விரைவாக திறக்கும்.',
    play: 'இயக்கு',
    stop: 'நிறுத்து',
    addToHomeScreen: 'முதற்பக்கத்தில் சேர்க்க',
    evidenceTitle: 'விளக்கம் மற்றும் ஆய்வுகள்',
    platformTitle: 'PWA மற்றும் தளம் வேறுபாடுகள்',
    simpleExplanationTitle: 'சுருக்கமான விளக்கம்',
    volumeLabel: 'ஒலி அளவு',
    timerLabel: 'டைமர்',
    timerOff: 'ஆஃப்',
    installInfo: 'நிறுவல் தகவலைக் காட்டு',
    addHome: 'முதற்பக்கத்தில் சேர்க்க',
    aboutBackground: 'பின்னணி இயக்கம் பற்றி',
    noiseType: 'ஒலி வகை',
    noisePapers: 'ஒலி ஆய்வுகளைக் காட்டு',
    noiseReferences: 'ஒலி ஆய்வுகளின் குறிப்புகள்',
    binauralOn: 'பைனரல் பீட்ஸ் ஆன்',
    binauralHelp: 'பைனரல் பீட் உதவியைக் காட்டு',
    binauralDesc: 'ஒவ்வொரு காதுக்கும் சற்று வித்தியாசமான ஒலிகளை அனுப்புகிறது, இதனால் பீட் வித்தியாசத்தை இன்னும் தெளிவாக உணர முடியும்.',
    baseFreq: 'அடிப்படை அதிர்வெண்',
    currentBand: 'தற்போதைய பீட் பேண்ட்',
    footerNote: 'மருத்துவ ரீதியான உரிமைகோரல்கள் எதுவும் செய்யப்படவில்லை. எச்சரிக்கையுடன் பயன்படுத்தவும்.',
    minute: 'நி',
    second: 'வி'
  },
  jv: {
    appName: 'Noise Maker',
    appTagline: 'Prasaja lan anteng, mung swara sing arep kok rungokke.',
    install: 'Tambahna menyang layar ngarep',
    installHint: 'Yen ditambah menyang layar ngarep, mbukak app luwih cepet.',
    play: 'Puter',
    stop: 'Mandheg',
    addToHomeScreen: 'Tambahna menyang layar ngarep',
    evidenceTitle: 'Panjelasan lan artikel',
    platformTitle: 'PWA lan bedane platform',
    simpleExplanationTitle: 'Panjelasan cekak',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Mati',
    installInfo: 'Tampilake info instalasi',
    addHome: 'Tambah menyang layar ngarep',
    aboutBackground: 'Babagan puter ing mburi',
    noiseType: 'Tipe swara',
    noisePapers: 'Tampilake artikel swara',
    noiseReferences: 'Referensi kanggo studi swara',
    binauralOn: 'Ketukan binaural urip',
    binauralHelp: 'Tampilake pitulung ketukan binaural',
    binauralDesc: 'Ngirim nada sing rada beda menyang saben kuping supaya bedane ketukan bisa dirasakake luwih cetha.',
    baseFreq: 'Frekuensi dasar',
    currentBand: 'Band ketukan saiki',
    footerNote: 'Ora ana klaim medis. Gunakake kanthi teliti lan cocogake karo konteksmu.',
    minute: 'm',
    second: 's'
  },
  it: {
    appName: 'Noise Maker',
    appTagline: 'Semplice e tranquillo, solo il suono che vuoi ascoltare.',
    install: 'Aggiungi alla schermata Home',
    installHint: 'Aggiungendola alla Home, si avvia piu rapidamente.',
    play: 'Riproduci',
    stop: 'Ferma',
    addToHomeScreen: 'Aggiungi alla schermata Home',
    evidenceTitle: 'Spiegazione e studi',
    platformTitle: 'PWA e differenze di piattaforma',
    simpleExplanationTitle: 'Spiegazione breve',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Off',
    installInfo: 'Mostra info installazione',
    addHome: 'Aggiungi alla schermata iniziale',
    aboutBackground: 'Riproduzione in background',
    noiseType: 'Tipo di rumore',
    noisePapers: 'Mostra studi sul rumore',
    noiseReferences: 'Riferimenti per studi sul rumore',
    binauralOn: 'Battiti binaurali attivi',
    binauralHelp: 'Mostra aiuto battiti binaurali',
    binauralDesc: 'Invia toni leggermente diversi a ciascun orecchio in modo che la differenza di battito sia percepita piu chiaramente.',
    baseFreq: 'Frequenza base',
    currentBand: 'Banda di battito attuale',
    footerNote: 'Non si effettuano affermazioni mediche. Usalo con cautela e adattalo al tuo contesto.',
    minute: 'm',
    second: 's'
  },
  fr: {
    appName: 'Noise Maker',
    appTagline: 'Simple et calme, uniquement le son que vous voulez.',
    install: 'Ajouter a l ecran d accueil',
    installHint: 'L ajout a l ecran d accueil accelere le lancement.',
    play: 'Lire',
    stop: 'Arreter',
    addToHomeScreen: 'Ajouter a l ecran d accueil',
    evidenceTitle: 'Explication et etudes',
    platformTitle: 'PWA et differences de plateforme',
    simpleExplanationTitle: 'Explication courte',
    volumeLabel: 'Volume',
    timerLabel: 'Minuteur',
    timerOff: 'Off',
    installInfo: 'Afficher les infos d installation',
    addHome: 'Ajouter a l ecran d accueil',
    aboutBackground: 'A propos de la lecture en arriere-plan',
    noiseType: 'Type de bruit',
    noisePapers: 'Afficher les etudes sur le bruit',
    noiseReferences: 'References pour les etudes sur le bruit',
    binauralOn: 'Battements binauraux actifs',
    binauralHelp: 'Afficher l aide sur les battements',
    binauralDesc: 'Envoie des sons legerement differents a chaque oreille pour que la difference de battement soit percue plus clairement.',
    baseFreq: 'Frequence de base',
    currentBand: 'Bande de battement actuelle',
    footerNote: 'Aucune reclamation medicale n est faite. Utilisez-le avec prudence et adaptez-le a votre contexte.',
    minute: 'm',
    second: 's'
  },
  de: {
    appName: 'Noise Maker',
    appTagline: 'Einfach und ruhig, nur der Klang, den du horen willst.',
    install: 'Zum Startbildschirm hinzufugen',
    installHint: 'Mit Startbildschirm startet die App schneller.',
    play: 'Abspielen',
    stop: 'Stoppen',
    addToHomeScreen: 'Zum Startbildschirm hinzufugen',
    evidenceTitle: 'Erklarung und Studien',
    platformTitle: 'PWA und Plattformunterschiede',
    simpleExplanationTitle: 'Kurze Erklarung',
    volumeLabel: 'Lautstarke',
    timerLabel: 'Timer',
    timerOff: 'Aus',
    installInfo: 'Installationsinfo anzeigen',
    addHome: 'Zum Startbildschirm hinzufugen',
    aboutBackground: 'Uber Hintergrundwiedergabe',
    noiseType: 'Rauschtyp',
    noisePapers: 'Rauschstudien anzeigen',
    noiseReferences: 'Referenzen fur Rauschstudien',
    binauralOn: 'Binaurale Beats an',
    binauralHelp: 'Hilfe zu binauralen Beats',
    binauralDesc: 'Sendet leicht unterschiedliche Tone an jedes Ohr, damit der Beat-Unterschied deutlicher wahrgenommen werden kann.',
    baseFreq: 'Basisfrequenz',
    currentBand: 'Aktuelles Beat-Band',
    footerNote: 'Es werden keine medizinischen Anspruche erhoben. Vorsichtig verwenden und an den Kontext anpassen.',
    minute: 'm',
    second: 's'
  },
  id: {
    appName: 'Noise Maker',
    appTagline: 'Sederhana dan tenang, hanya suara yang ingin kamu dengar.',
    install: 'Tambahkan ke layar utama',
    installHint: 'Menambahkan ke layar utama membuat aplikasi lebih cepat dibuka.',
    play: 'Putar',
    stop: 'Hentikan',
    addToHomeScreen: 'Tambahkan ke layar utama',
    evidenceTitle: 'Penjelasan dan studi',
    platformTitle: 'PWA dan perbedaan platform',
    simpleExplanationTitle: 'Penjelasan singkat',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Mati',
    installInfo: 'Tampilkan info instalasi',
    addHome: 'Tambahkan ke layar utama',
    aboutBackground: 'Tentang pemutaran latar belakang',
    noiseType: 'Tipe kebisingan',
    noisePapers: 'Tampilkan studi kebisingan',
    noiseReferences: 'Referensi untuk studi kebisingan',
    binauralOn: 'Ketukan binaural aktif',
    binauralHelp: 'Tampilkan bantuan ketukan binaural',
    binauralDesc: 'Mengirimkan nada yang sedikit berbeda ke setiap telinga sehingga perbedaan ketukan dapat dirasakan lebih jelas.',
    baseFreq: 'Frekuensi dasar',
    currentBand: 'Pita ketukan saat ini',
    footerNote: 'Tidak ada klaim medis yang dibuat. Gunakan dengan hati-hati dan sesuaikan dengan konteks Anda.',
    minute: 'm',
    second: 's'
  }
};

export function resolveLocalizedText(text: LocalizedText, locale: Locale): string {
  return text[locale] ?? text.en ?? text.ja;
}

function resolveLocalizedList(list: LocalizedList, locale: Locale): string[] {
  return list[locale] ?? list.en ?? list.ja;
}

export const noiseTypes: Array<{
  key: NoiseType;
  label: LocalizedText;
  short: LocalizedText;
}> = [
  { 
    key: 'white', 
    label: { ja: 'ホワイト', en: 'White', 'zh-Hans': '白噪音', es: 'Blanco', ko: '화이트', fr: 'Blanc', de: 'Weiß' }, 
    short: { 
      ja: '環境音を目立ちにくくして、作業や休憩の切り替えに使われることがあります。', 
      en: 'Often used to mask background sounds and support task or rest transitions.',
      'zh-Hans': '通常用于遮蔽背景噪音，支持工作或休息的切换。',
      es: 'A menudo se usa para enmascarar sonidos de fondo y apoyar transiciones de tareas.',
      ko: '주변 소음을 차단하고 작업이나 휴식의 전환을 돕는 데 사용됩니다.',
      fr: 'Souvent utilisé pour masquer les bruits de fond et faciliter les transitions.',
      de: 'Wird oft verwendet, um Hintergrundgeräusche zu maskieren.'
    } 
  },
  { 
    key: 'pink', 
    label: { ja: 'ピンク', en: 'Pink', 'zh-Hans': '粉红噪音', es: 'Rosa', ko: '핑크', fr: 'Rose', de: 'Rosa' }, 
    short: { 
      ja: '就寝前に落ち着きやすいと感じる人がいます。睡眠への効果は研究でも個人差があります。', 
      en: 'Some people find it easier to settle before sleep. Sleep effects vary across studies.',
      'zh-Hans': '有些人觉得睡前更容易安静。睡眠效果在研究中因人而异。',
      es: 'A algunas personas les resulta más fácil calmarse antes de dormir.',
      ko: '취침 전에 마음을 진정시키는 데 도움이 될 수 있습니다. 수면 효과는 개인차가 있습니다.',
      fr: 'Certaines personnes le trouvent apaisant avant de dormir.',
      de: 'Manche finden es vor dem Schlafengehen beruhigend.'
    } 
  },
  { 
    key: 'brown', 
    label: { ja: 'ブラウン', en: 'Brown', 'zh-Hans': '褐噪音', es: 'Marrón', ko: '브라운', fr: 'Brun', de: 'Braun' }, 
    short: { 
      ja: '低めで包まれる感覚があり、リラックス目的で選ばれることがあります。', 
      en: 'Its deeper tone can feel enveloping, so some listeners choose it for relaxation.',
      'zh-Hans': '低沉的包围感，常被用于放松目的。',
      es: 'Su tono más profundo puede sentirse envolvente, ideal para la relajación.',
      ko: '낮은 톤으로 감싸이는 느낌이 있어 휴식을 위해 선택되기도 합니다.',
      fr: 'Son ton plus profond peut sembler enveloppant, idéal pour la relaxation.',
      de: 'Sein tieferer Ton kann sich einhüllend anfühlen, ideal zur Entspannung.'
    } 
  },
  { 
    key: 'blue', 
    label: { ja: 'ブルー', en: 'Blue', 'zh-Hans': '蓝噪音', es: 'Azul', ko: '블루', fr: 'Bleu', de: 'Blau' }, 
    short: { 
      ja: '気分を切り替えたい場面で、短時間の集中スイッチとして使う人もいます。', 
      en: 'Sometimes used as a short focus reset when people want a quick mental shift.',
      'zh-Hans': '在需要转换心情时，有人将其作为短时间集中的开关。',
      es: 'A veces se usa como un breve reinicio de enfoque para un cambio mental rápido.',
      ko: '기분 전환이 필요한 상황에서 단시간 집중을 위한 스위치로 사용되기도 합니다.',
      fr: 'Parfois utilisé pour réinitialiser la concentration rapidement.',
      de: 'Wird manchmal für einen kurzen Fokus-Reset verwendet.'
    } 
  },
  { 
    key: 'violet', 
    label: { ja: 'ヴァイオレット', en: 'Violet', 'zh-Hans': '紫噪音', es: 'Violeta', ko: '바이올렛', fr: 'Violet', de: 'Violett' }, 
    short: { 
      ja: '高めの刺激で注意を向けやすいと感じる人がいますが、長時間は疲れやすいことがあります。', 
      en: 'Some listeners feel more alert with it, though long sessions can be fatiguing.',
      'zh-Hans': '高频率刺激让人更容易集中注意力，但长时间使用可能会疲劳。',
      es: 'Algunos oyentes se sienten más alerta, aunque sesiones largas pueden fatigar.',
      ko: '높은 자극으로 주의를 끌기 쉽지만, 장시간 사용 시 피로할 수 있습니다.',
      fr: 'Certains auditeurs se sentent plus alertes, mais cela peut être fatiguant.',
      de: 'Manche fühlen sich wacher, aber lange Sitzungen können ermüdend sein.'
    } 
  }
];

export const binauralBands: Array<{
  key: string;
  min: number;
  max: number;
  label: LocalizedText;
  effect: LocalizedText;
}> = [
  {
    key: 'delta',
    min: 0.5,
    max: 4,
    label: { ja: 'デルタ (0.5-4 Hz)', en: 'Delta (0.5-4 Hz)', 'zh-Hans': 'Delta (0.5-4 Hz)', ko: '델타 (0.5-4 Hz)' },
    effect: {
      ja: '深い休息モードに寄せたいときの目安です。夜の静かな時間に合わせやすい帯域です。',
      en: 'A common target when aiming for a deeper rest mood, especially in quiet night sessions.',
      'zh-Hans': '想要进入深度休息模式时的参考，适合安静的夜晚。',
      es: 'Un objetivo común para un estado de descanso profundo, especialmente de noche.',
      ko: '깊은 휴식 모드를 원할 때의 기준입니다. 조용한 밤 시간에 적합합니다.',
      fr: 'Idéal pour un repos profond, surtout lors de sessions nocturnes calmes.',
      de: 'Ein häufiges Ziel für tiefe Ruhe, besonders in ruhigen Nachtsitzungen.'
    }
  },
  {
    key: 'theta',
    min: 4,
    max: 8,
    label: { ja: 'シータ (4-8 Hz)', en: 'Theta (4-8 Hz)', 'zh-Hans': 'Theta (4-8 Hz)', ko: '시타 (4-8 Hz)' },
    effect: {
      ja: '落ち着きや内省の感覚と結びつけられることがあります。体感は人によって大きく変わります。',
      en: 'Sometimes linked to calm or inward attention, with large person-to-person variation.',
      'zh-Hans': '有时与平静或内省感相关。体感因人而异。',
      es: 'A veces vinculado a la calma o atención interior, con gran variación personal.',
      ko: '진정이나 내면의 성찰과 연결되기도 합니다. 체감은 사람에 따라 다릅니다.',
      fr: 'Parfois lié au calme ou à l attention intérieure, varie selon les personnes.',
      de: 'Manchmal mit Ruhe oder innerer Aufmerksamkeit verbunden.'
    }
  },
  {
    key: 'alpha',
    min: 8,
    max: 13,
    label: { ja: 'アルファ (8-13 Hz)', en: 'Alpha (8-13 Hz)', 'zh-Hans': 'Alpha (8-13 Hz)', ko: '알파 (8-13 Hz)' },
    effect: {
      ja: 'リラックスしつつ作業したいときに選ばれやすい、バランス型の帯域です。',
      en: 'A balanced range often chosen for relaxed but awake sessions.',
      'zh-Hans': '平衡型频带，常用于在放松的同时进行工作。',
      es: 'Un rango equilibrado a menudo elegido para sesiones relajadas pero despiertas.',
      ko: '휴식하면서 작업하고 싶을 때 선택하기 좋은 밸런스형 대역입니다.',
      fr: 'Une plage équilibrée souvent choisie pour des sessions relaxantes mais éveillées.',
      de: 'Ein ausgewogener Bereich für entspannte, aber wache Sitzungen.'
    }
  },
  {
    key: 'beta',
    min: 13,
    max: 30,
    label: { ja: 'ベータ (13-30 Hz)', en: 'Beta (13-30 Hz)', 'zh-Hans': 'Beta (13-30 Hz)', ko: '베타 (13-30 Hz)' },
    effect: {
      ja: '注意や課題集中に関連づけられる帯域です。人によっては刺激が強すぎる場合があります。',
      en: 'Often associated with attention and task focus, though it may feel overstimulating.',
      'zh-Hans': '与注意力和任务集中相关的频带。对某些人来说可能过于刺激。',
      es: 'Asociado con la atención y el enfoque, aunque puede resultar sobreestimulante.',
      ko: '주의력이나 과제 집중과 관련된 대역입니다. 자극이 너무 강하게 느껴질 수 있습니다.',
      fr: 'Associé à l attention et à la concentration, peut être surstimulant.',
      de: 'Verbunden mit Aufmerksamkeit und Fokus, kann überstimulierend sein.'
    }
  },
  {
    key: 'gamma',
    min: 30,
    max: 40,
    label: { ja: 'ガンマ (30-40 Hz)', en: 'Gamma (30-40 Hz)', 'zh-Hans': 'Gamma (30-40 Hz)', ko: '감마 (30-40 Hz)' },
    effect: {
      ja: '切り替えや短時間の高集中に向けた高めの帯域です。刺激が強く感じる場合があります。',
      en: 'A higher band often used for short, high-focus pushes; it can feel intense.',
      'zh-Hans': '用于切换心情或短时间高度集中的高频带。可能会感到强烈刺激。',
      es: 'Una banda superior para ráfagas de alta concentración; puede sentirse intensa.',
      ko: '전환이나 단시간 고집중을 위한 높은 대역입니다. 자극이 강할 수 있습니다.',
      fr: 'Une bande plus élevée pour une concentration intense et courte.',
      de: 'Ein höheres Band für kurze, hochkonzentrierte Phasen.'
    }
  }
];

export const evidenceCards: EvidenceCard[] = [
  { 
    key: 'noise-colors', 
    title: { ja: 'ノイズ色の違い', en: 'Differences between noise colors', 'zh-Hans': '噪音颜色的区别', es: 'Diferencias entre colores de ruido', ko: '노이즈 색상의 차이' }, 
    summary: { 
      ja: '白・ピンク・ブラウン・ブルー・ヴァイオレットは、周波数ごとの強さが違う音です。効果を断定せず、まずは音の性質として扱います。', 
      en: 'White, pink, brown, blue, and violet noise differ by frequency weighting. The app treats them as sound-shape tools.',
      'zh-Hans': '不同颜色的噪音具有不同的频率权重。本应用将其视为声音塑造工具。',
      es: 'Los ruidos difieren según la ponderación de frecuencia. Se tratan como herramientas de sonido.',
      ko: '각 노이즈는 주파수 가중치에 따라 다릅니다. 이 앱은 이를 의학적 치료가 아닌 소리 도구로 취급합니다.',
      fr: 'Les bruits diffèrent selon la pondération de fréquence. Traités comme des outils sonores.',
      de: 'Rauschen unterscheidet sich durch Frequenzgewichtung.'
    }, 
    strength: 'Strong', 
    caveat: { 
      ja: '音響的な違いは明確ですが、使い方による体感は個人差があります。', 
      en: 'The spectral differences are clear, but user experience varies a lot.',
      'zh-Hans': '频谱差异明显，但用户体验因人而异。',
      es: 'Las diferencias espectrales son claras, pero la experiencia del usuario varía.',
      ko: '음향적 차이는 명확하지만, 체감은 개인마다 다릅니다.',
      fr: 'Les différences spectrales sont claires, mais l expérience varie.',
      de: 'Spektrale Unterschiede sind klar, aber die Erfahrung variiert.'
    }, 
    links: [{ label: 'Pink noise and auditory stimulation review', url: 'https://pubmed.ncbi.nlm.nih.gov/34964434/' }, { label: 'Pink noise and NREM sleep review', url: 'https://pubmed.ncbi.nlm.nih.gov/32765139/' }] 
  },
  { 
    key: 'binaural-beats', 
    title: { ja: 'バイノーラルビート', en: 'Binaural beats', 'zh-Hans': '双耳节拍', es: 'Pulsos binaurales', ko: '바이노럴 비트' }, 
    summary: { 
      ja: '左右の耳に少し違う周波数を出して、差分のうなりを知覚させます。研究はありますが、結果は一貫していません。', 
      en: 'Two nearby tones are sent separately to each ear so the listener perceives a beat. Results are inconsistent.',
      'zh-Hans': '向每只耳朵发送略有不同的频率，使用户感知到节拍。研究结果并不一致。',
      es: 'Se envían tonos cercanos a cada oído para percibir un pulso. Los resultados son inconsistentes.',
      ko: '양쪽 귀에 서로 다른 주파수를 보내 맥박을 느끼게 합니다. 연구 결과는 일관되지 않습니다.',
      fr: 'Deux tons proches sont envoyés à chaque oreille pour percevoir un battement.',
      de: 'Zwei Töne werden separat an jedes Ohr gesendet.'
    }, 
    strength: 'Mixed', 
    caveat: { 
      ja: '睡眠改善、不安軽減、ADHD 改善などを断定しません。可能性はあっても、結論は控えめに扱います。', 
      en: 'No claims are made about sleep, anxiety, or ADHD. Effects are described cautiously.',
      'zh-Hans': '不确定睡眠改善、减轻焦虑等效果。结论保持谨慎。',
      es: 'No se hacen afirmaciones sobre el sueño o la ansiedad. Los efectos se describen con cautela.',
      ko: '수면 개선이나 불안 완화 등을 단정하지 않습니다. 효과는 신중하게 설명됩니다.',
      fr: 'Aucune affirmation sur le sommeil ou l anxiété. Les effets sont décrits avec prudence.',
      de: 'Keine Behauptungen über Schlaf oder Angst.'
    }, 
    links: [{ label: 'Systematic review on binaural beats and brain oscillatory activity', url: 'https://pubmed.ncbi.nlm.nih.gov/37205669/' }, { label: 'Systematic review and meta-review on binaural beats', url: 'https://pubmed.ncbi.nlm.nih.gov/38458383/' }] 
  }
];

const platformNotes: LocalizedList = {
  ja: ['iOS はブラウザの制限が強く、バックグラウンド再生は OS の状態に左右されます。', 'Android は PWA と Media Session が比較的素直に動きますが、省電力設定で止まることがあります。', 'Desktop は最も安定しますが、タブを閉じると当然停止します。'],
  en: ['iOS has stricter browser limits, so background playback depends on OS behavior.', 'Android usually handles PWA and Media Session well, but battery optimization can interrupt.', 'Desktop is the most stable, though closing the tab will stop playback.'],
  'zh-Hans': ['iOS 浏览器限制较多，后台播放取决于系统状态。', 'Android 的 PWA 和媒体会话运行较顺畅，但省电设置可能会中断。', '桌面版最稳定，但关闭标签页会停止。'],
  es: ['iOS tiene límites más estrictos, la reproducción depende del comportamiento del OS.', 'Android suele manejar bien PWA, pero la optimización de batería puede interrumpir.', 'Escritorio es lo más estable, aunque cerrar la pestaña detendrá la reproducción.'],
  ko: ['iOS는 브라우저 제한이 엄격하여 백그라운드 재생은 OS 상태에 따라 달라집니다.', 'Android는 PWA와 Media Session이 잘 작동하지만, 절전 설정으로 인해 중단될 수 있습니다.', '데스크톱은 가장 안정적이지만, 탭을 닫으면 중단됩니다.'],
  fr: ['iOS a des limites plus strictes, la lecture dépend du comportement de l OS.', 'Android gère généralement bien les PWA, mais l optimisation peut interrompre.', 'Le bureau est le plus stable, mais fermer l onglet arrêtera la lecture.'],
  de: ['iOS hat strengere Grenzen, die Wiedergabe hängt vom OS ab.', 'Android funktioniert meist gut, aber die Akkuoptimierung kann unterbrechen.', 'Desktop ist am stabilsten, aber das Schließen des Tabs stoppt alles.']
};

export function getPlatformNotes(locale: Locale): string[] {
  return resolveLocalizedList(platformNotes, locale);
}

export const timerOptions = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60] as const;

export function getNoiseLabel(locale: Locale, key: NoiseType): string {
  const item = noiseTypes.find((noiseType) => noiseType.key === key);
  return item ? resolveLocalizedText(item.label, locale) : key;
}