import type { Copy, EvidenceCard, Locale, LocalizedList, LocalizedText, NoiseType, Preset } from './types';

export const copy: Record<Locale, Copy> = {
  ja: {
    appName: 'Noise Maker',
    appTagline: 'シンプルに、静かに、聞きたい音だけ。',
    install: 'ホーム画面に追加',
    installHint: 'ホーム画面に追加すると、起動が速くなります。',
    play: '再生',
    stop: '停止',
    addToHomeScreen: 'ホーム画面に追加',
    evidenceTitle: '説明と論文',
    platformTitle: 'PWA と端末差分',
    simpleExplanationTitle: '短い説明',
    volumeLabel: '音量',
    timerLabel: 'タイマー',
    timerOff: 'なし',
    installInfo: 'インストール情報を表示',
    addHome: 'ホーム画面に追加',
    aboutBackground: 'バックグラウンドでの動作について',
    noiseType: 'ノイズタイプ',
    noisePapers: 'ノイズの論文リンクを表示',
    noiseReferences: 'ノイズに関する参考論文',
    beatOn: 'ビート ON',
    beatHelp: 'ビートの説明を表示',
    beatDesc: '左右で異なる音（バイノーラル）または等間隔のパルス（アイソクロニック）を流し、集中や休息を助ける機能です。',
    earphoneMode: 'イヤホン（バイノーラル）',
    speakerMode: 'スピーカー（アイソクロニック）',
    baseFreq: 'ベース周波数',
    currentBand: '実際の再生周波数',
    footerNote: '医療効果を保証するものではありません。用途に合わせて慎重に使ってください。',
    minute: '分',
    second: '秒',
    iosStep1: '共有ボタン（四角に上矢印）をタップします。',
    iosStep2: '下にスクロールして「ホーム画面に追加」をタップします。',
    iosStep3: '右上の「追加」をタップします。',
    androidStep1: 'ブラウザの3点リーダーメニューをタップします。',
    androidStep2: '「アプリをインストール」または「ホーム画面に追加」をタップします。',
    gotIt: '了解',
    close: '閉じる',
    presetsTitle: 'クイックプリセット',
    resetPreset: '設定をリセット',
    settingsTitle: '詳細設定',
    advancedSettings: '詳細設定を表示',
    noiseOff: 'オフ'
  },
  en: {
    appName: 'Noise Maker',
    appTagline: 'Simple noise and beats, tuned for phones.',
    install: 'Add to Home Screen',
    installHint: 'Adding to the home screen makes launch faster.',
    play: 'Play',
    stop: 'Stop',
    addToHomeScreen: 'Add to Home Screen',
    evidenceTitle: 'Explanation and papers',
    platformTitle: 'PWA and platform differences',
    simpleExplanationTitle: 'Plain explanation',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Off',
    installInfo: 'Show installation info',
    addHome: 'Add to home screen',
    aboutBackground: 'About background playback',
    noiseType: 'Noise type',
    noisePapers: 'Show noise papers',
    noiseReferences: 'References for noise studies',
    beatOn: 'Beat on',
    beatHelp: 'Show beat help',
    beatDesc: 'This sends slightly different tones to each ear (binaural) or pulsed tones (isochronic) to help focus or rest.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Base frequency',
    currentBand: 'Current playback frequencies',
    footerNote: 'No medical claims are made. Use it cautiously and fit it to your context.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tap the Share button (square with arrow up).',
    iosStep2: 'Scroll down and tap "Add to Home Screen".',
    iosStep3: 'Tap "Add" in the top right.',
    androidStep1: 'Tap the three-dot menu in the browser.',
    androidStep2: 'Tap "Install app" or "Add to home screen".',
    gotIt: 'Got it',
    close: 'Close',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  'zh-Hans': {
    appName: 'Noise Maker',
    appTagline: '简洁、安静，只播放你想听的声音。',
    install: '添加到主屏幕',
    installHint: '添加到主屏幕后，启动会更快。',
    play: '播放',
    stop: '停止',
    addToHomeScreen: '添加到主屏幕',
    evidenceTitle: '说明与论文',
    platformTitle: 'PWA 与设备差异',
    simpleExplanationTitle: '简短说明',
    volumeLabel: '音量',
    timerLabel: '计时器',
    timerOff: '关闭',
    installInfo: '显示安装信息',
    addHome: '添加到主屏幕',
    aboutBackground: '关于后台播放',
    noiseType: '噪音类型',
    noisePapers: '显示噪音论文',
    noiseReferences: '噪音研究参考',
    beatOn: '开启双耳节拍',
    beatHelp: '显示双耳节拍帮助',
    beatDesc: '向每只耳朵发送略有不同的音调，以便更清晰地感知节拍差异。',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: '基准频率',
    currentBand: '当前节拍频带',
    footerNote: '不作医疗声明。请谨慎使用并适应您的环境。',
    minute: '分',
    second: '秒',
    iosStep1: '点击“分享”按钮（带上箭头的方块）。',
    iosStep2: '向下滚动并点击“添加到主屏幕”。',
    iosStep3: '点击右上角的“添加”。',
    androidStep1: '点击浏览器中的三点菜单。',
    androidStep2: '点击“安装应用”或“添加到主屏幕”。',
    gotIt: '知道了',
    close: '关闭',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  es: {
    appName: 'Noise Maker',
    appTagline: 'Simple, tranquilo, solo el sonido que quieres.',
    install: 'Agregar a pantalla de inicio',
    installHint: 'Agregarla a la pantalla de inicio acelera el inicio.',
    play: 'Reproducir',
    stop: 'Detener',
    addToHomeScreen: 'Agregar a pantalla de inicio',
    evidenceTitle: 'Explicación y estudios',
    platformTitle: 'PWA y diferencias de plataforma',
    simpleExplanationTitle: 'Explicación breve',
    volumeLabel: 'Volumen',
    timerLabel: 'Temporizador',
    timerOff: 'Desactivado',
    installInfo: 'Mostrar info de instalación',
    addHome: 'Agregar a la pantalla de inicio',
    aboutBackground: 'Sobre reproducción en segundo plano',
    noiseType: 'Tipo de ruido',
    noisePapers: 'Mostrar estudios de ruido',
    noiseReferences: 'Referencias para estudios de ruido',
    beatOn: 'Pulsos binaurales activados',
    beatHelp: 'Mostrar ayuda de pulsos binaurales',
    beatDesc: 'Envía tonos ligeramente diferentes a cada oído para que la diferencia de pulso se perciba más claramente.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Frecuencia base',
    currentBand: 'Banda de pulso actual',
    footerNote: 'No se realizan afirmaciones médicas. Úselo con precaución y adáptelo a su contexto.',
    minute: 'm',
    second: 's',
    iosStep1: 'Toca el botón Compartir (cuadrado con flecha arriba).',
    iosStep2: 'Desplázate hacia abajo y toca "Agregar a pantalla de inicio".',
    iosStep3: 'Toca "Agregar" en la esquina superior derecha.',
    androidStep1: 'Toca el menú de tres puntos en el navegador.',
    androidStep2: 'Toca "Instalar aplicación" o "Agregar a pantalla de inicio".',
    gotIt: 'Entendido',
    close: 'Cerrar',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  hi: {
    appName: 'Noise Maker',
    appTagline: 'सरल, शांत, बस वही ध्वनि जो आप सुनना चाहें।',
    install: 'होम स्क्रीन पर जोड़ें',
    installHint: 'होम स्क्रीन पर जोड़ने से ऐप जल्दी खुलता है।',
    play: 'चलाएँ',
    stop: 'रोकें',
    addToHomeScreen: 'होम स्क्रीन पर जोड़ें',
    evidenceTitle: 'व्याख्या और शोध पत्र',
    platformTitle: 'PWA और प्लेटफ़ॉर्म अंतर',
    simpleExplanationTitle: 'संक्षिप्त व्याख्या',
    volumeLabel: 'आवाज़',
    timerLabel: 'टाइमर',
    timerOff: 'बंद',
    installInfo: 'इंस्टॉलेशन जानकारी दिखाएं',
    addHome: 'होम स्क्रीन पर जोड़ें',
    aboutBackground: 'बैकग्राउंड प्लेबैक के बारे में',
    noiseType: 'शोर का प्रकार',
    noisePapers: 'शोर शोध पत्र दिखाएं',
    noiseReferences: 'शोर अध्ययन के संदर्भ',
    beatOn: 'बाइनोरल बीट्स चालू',
    beatHelp: 'बाइनोरल बीट सहायता दिखाएं',
    beatDesc: 'प्रत्येक कान में थोड़े अलग टोन भेजता है ताकि बीट अंतर को अधिक स्पष्ट रूप से समझा जा सके।',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'आधार आवृत्ति',
    currentBand: 'वर्तमान बीट बैंड',
    footerNote: 'कोई चिकित्सा दावा नहीं किया गया है। इसका सावधानीपूर्वक उपयोग करें और अपने संदर्भ के अनुसार ढालें।',
    minute: 'म',
    second: 'से',
    iosStep1: 'शेयर बटन (ऊपर तीर वाला वर्ग) पर टैप करें।',
    iosStep2: 'नीचे स्क्रॉल करें और "होम स्क्रीन पर जोड़ें" पर टैप करें।',
    iosStep3: 'ऊपर दाईं ओर "जोड़ें" पर टैप करें।',
    androidStep1: 'ब्राउज़र में तीन-बिंदू वाले मेनू पर टैप करें।',
    androidStep2: '"ऐप इंस्टॉल करें" या "होम स्क्रीन पर जोड़ें" पर टैप करें।',
    gotIt: 'समझ गए',
    close: 'बंद करें',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  bn: {
    appName: 'Noise Maker',
    appTagline: 'সহজ, শান্ত, শুধু আপনার পছন্দের শব্দ।',
    install: 'হোম স্ক্রিনে যোগ করুন',
    installHint: 'হোম স্ক্রিনে যোগ করলে দ্রুত চালু হবে।',
    play: 'চালু',
    stop: 'বন্ধ',
    addToHomeScreen: 'হোম স্ক্রিনে যোগ করুন',
    evidenceTitle: 'ব্যাখ্যা ও গবেষণা',
    platformTitle: 'PWA ও প্ল্যাটফর্ম পার্থক্য',
    simpleExplanationTitle: 'সংক্ষিপ্ত ব্যাখ্যা',
    volumeLabel: 'ভলিউম',
    timerLabel: 'টাইমার',
    timerOff: 'বন্ধ',
    installInfo: 'ইনস্টলেশন তথ্য দেখান',
    addHome: 'হোম স্ক্রিনে যোগ করুন',
    aboutBackground: 'ব্যাকগ্রাউন্ড প্লেব্যাক সম্পর্কে',
    noiseType: 'শব্দের ধরণ',
    noisePapers: 'শব্দ গবেষণা পত্র দেখান',
    noiseReferences: 'শব্দ অধ্যয়নের রেফারেন্স',
    beatOn: 'বাইনরাল বিটস চালু',
    beatHelp: 'বাইনরাল বিট সহায়তা দেখান',
    beatDesc: 'প্রতিটি কানে সামান্য ভিন্ন সুর পাঠায় যাতে বিট পার্থক্য আরও স্পষ্টভাবে বোঝা যায়।',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'বেস ফ্রিকোয়েন্সি',
    currentBand: 'বর্তমান বিট ব্যান্ড',
    footerNote: 'কোন চিকিৎসা দাবি করা হয় না। এটি সাবধানতার সাথে ব্যবহার করুন এবং আপনার প্রেক্ষাপটের সাথে খাপ খাইয়ে নিন।',
    minute: 'মি',
    second: 'সে',
    iosStep1: 'শেয়ার বোতামটি (উপরে তীর সহ বর্গক্ষেত্র) আলতো চাপুন।',
    iosStep2: 'নিচে স্ক্রোল করুন এবং "হোম স্ক্রিনে যোগ করুন" আলতো চাপুন।',
    iosStep3: 'উপরে ডানদিকে "যোগ করুন" আলতো চাপুন।',
    androidStep1: 'ব্রাউজারে তিন-বিন্দু মেনু আলতো চাপুন।',
    androidStep2: '"অ্যাপ ইনস্টল করুন" বা "হোম স্ক্রিনে যোগ করুন" আলতো চাপুন।',
    gotIt: 'বুঝেছি',
    close: 'বন্ধ করুন',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  pt: {
    appName: 'Noise Maker',
    appTagline: 'Simples e calmo, apenas o som que voce quer ouvir.',
    install: 'Adicionar a tela inicial',
    installHint: 'Adicionar a tela inicial deixa a abertura mais rapida.',
    play: 'Reproduzir',
    stop: 'Parar',
    addToHomeScreen: 'Adicionar a tela inicial',
    evidenceTitle: 'Explicacao e artigos',
    platformTitle: 'PWA e diferencas de plataforma',
    simpleExplanationTitle: 'Explicacao curta',
    volumeLabel: 'Volume',
    timerLabel: 'Temporizador',
    timerOff: 'Desligado',
    installInfo: 'Mostrar info de instalacao',
    addHome: 'Adicionar a tela inicial',
    aboutBackground: 'Sobre reproducao em segundo plano',
    noiseType: 'Tipo de ruido',
    noisePapers: 'Mostrar artigos de ruido',
    noiseReferences: 'Referencias para estudos de ruido',
    beatOn: 'Batidas binaurais ligadas',
    beatHelp: 'Mostrar ajuda de batidas binaurais',
    beatDesc: 'Envia tons ligeiramente diferentes para cada ouvido para que a diferenca de batida seja percebida mais claramente.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Frequencia base',
    currentBand: 'Banda de batida atual',
    footerNote: 'Nenhuma alegacao medica e feita. Use com cautela e adapte ao seu contexto.',
    minute: 'm',
    second: 's',
    iosStep1: 'Toque no botão Compartilhar (quadrado com seta para cima).',
    iosStep2: 'Role para baixo e toque em "Adicionar à Tela de Início".',
    iosStep3: 'Toque em "Adicionar" no canto superior direito.',
    androidStep1: 'Toque no menu de três pontos no navegador.',
    androidStep2: 'Toque em "Instalar aplicativo" ou "Adicionar à tela inicial".',
    gotIt: 'Entendido',
    close: 'Fechar',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  ru: {
    appName: 'Noise Maker',
    appTagline: 'Просто, спокойно, только нужный вам звук.',
    install: 'Добавить на главный экран',
    installHint: 'Добавление на главный экран ускоряет запуск.',
    play: 'Воспроизвести',
    stop: 'Остановить',
    addToHomeScreen: 'Добавить на главный экран',
    evidenceTitle: 'Объяснение и статьи',
    platformTitle: 'PWA и различия платформ',
    simpleExplanationTitle: 'Краткое объяснение',
    volumeLabel: 'Громкость',
    timerLabel: 'Таймер',
    timerOff: 'Выкл',
    installInfo: 'Показать инфо об установке',
    addHome: 'Добавить на главный экран',
    aboutBackground: 'О фоновом воспроизведении',
    noiseType: 'Тип шума',
    noisePapers: 'Показать статьи о шуме',
    noiseReferences: 'Ссылки на исследования шума',
    beatOn: 'Бинауральные ритмы вкл',
    beatHelp: 'Показать справку по ритмам',
    beatDesc: 'Подает слегка разные тона в каждое ухо, чтобы разница ритмов воспринималась четче.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Базовая частота',
    currentBand: 'Текущий диапазон ритма',
    footerNote: 'Медицинские заявления не делаются. Используйте с осторожностью и адаптируйте под себя.',
    minute: 'мин',
    second: 'сек',
    iosStep1: 'Нажмите кнопку «Поделиться» (квадрат со стрелкой вверх).',
    iosStep2: 'Прокрутите вниз и нажмите «На экран "Домой"».',
    iosStep3: 'Нажмите «Добавить» в правом верхнем углу.',
    androidStep1: 'Нажмите на меню из трех точек в браузере.',
    androidStep2: 'Нажмите «Установить приложение» или «На экран "Домой"».',
    gotIt: 'Понятно',
    close: 'Закрыть',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  yue: {
    appName: 'Noise Maker',
    appTagline: '簡單、寧靜，只播你想聽嘅聲音。',
    install: '加入主畫面',
    installHint: '加入主畫面之後，啟動會更快。',
    play: '播放',
    stop: '停止',
    addToHomeScreen: '加入主畫面',
    evidenceTitle: '說明同論文',
    platformTitle: 'PWA 同平台差異',
    simpleExplanationTitle: '簡短說明',
    volumeLabel: '音量',
    timerLabel: '計時器',
    timerOff: '關閉',
    installInfo: '顯示安裝資訊',
    addHome: '加入主畫面',
    aboutBackground: '關於背景播放',
    noiseType: '噪音類型',
    noisePapers: '顯示噪音論文',
    noiseReferences: '噪音研究參考',
    beatOn: '開啟雙耳節拍',
    beatHelp: '顯示雙耳節拍說明',
    beatDesc: '向每隻耳仔發送略有不同嘅音調，以便更清晰地感知節拍差異。',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: '基準頻率',
    currentBand: '當前節拍頻帶',
    footerNote: '唔作醫療聲明。請謹慎使用並適應你嘅環境。',
    minute: '分',
    second: '秒',
    iosStep1: '撳「分享」掣（帶上箭頭嘅方塊）。',
    iosStep2: '向下捲動並撳「加入主畫面」。',
    iosStep3: '撳右上角嘅「加入」。',
    androidStep1: '撳瀏覽器入面個三點選單。',
    androidStep2: '撳「安裝應用程式」或者「加入主畫面」。',
    gotIt: '知道喇',
    close: '關閉',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  vi: {
    appName: 'Noise Maker',
    appTagline: 'Don gian, yen tinh, chi phat am thanh ban muon nghe.',
    install: 'Them vao man hinh chinh',
    installHint: 'Them vao man hinh chinh giup mo nhanh hon.',
    play: 'Phat',
    stop: 'Dung',
    addToHomeScreen: 'Them vao man hinh chinh',
    evidenceTitle: 'Giai thich va bai bao',
    platformTitle: 'PWA va khac biet nen tang',
    simpleExplanationTitle: 'Giai thich ngan',
    volumeLabel: 'Am luong',
    timerLabel: 'Hen gio',
    timerOff: 'Tat',
    installInfo: 'Hien thi thong tin cai dat',
    addHome: 'Them vao man hinh chinh',
    aboutBackground: 'Ve phat trong nen',
    noiseType: 'Loai tieng on',
    noisePapers: 'Hien thi bai bao ve tieng on',
    noiseReferences: 'Tai lieu tham khao tieng on',
    beatOn: 'Bat nhip binaural',
    beatHelp: 'Hien tro giup nhip binaural',
    beatDesc: 'Gui cac am thanh hoi khac nhau den moi tai de co the cam nhan su khac biet nhip ro rang hon.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Tan so co ban',
    currentBand: 'Bang nhip hien tai',
    footerNote: 'Khong co tuyen bo y te nao duoc dua ra. Su dung than trong va phu hop voi boi canh cua ban.',
    minute: 'p',
    second: 'g',
    iosStep1: 'Chạm vào nút Chia sẻ (hình vuông có mũi tên lên).',
    iosStep2: 'Cuộn xuống và chạm vào "Thêm vào màn hình chính".',
    iosStep3: 'Chạm vào "Thêm" ở góc trên bên phải.',
    androidStep1: 'Chạm vào menu ba dấu chấm trong trình duyệt.',
    androidStep2: 'Chạm vào "Cài đặt ứng dụng" hoặc "Thêm vào màn hình chính".',
    gotIt: 'Đã hiểu',
    close: 'Đóng',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  mr: {
    appName: 'Noise Maker',
    appTagline: 'सोपे, शांत, फक्त तुम्हाला हवे तेच आवाज.',
    install: 'ホーム画面に加',
    installHint: 'ホーム画面に加えると、起動が速くなります。',
    play: '再生',
    stop: '停止',
    addToHomeScreen: 'ホーム画面に加',
    evidenceTitle: '説明と論文',
    platformTitle: 'PWA と端末差分',
    simpleExplanationTitle: '短い説明',
    volumeLabel: '音量',
    timerLabel: 'タイマー',
    timerOff: 'なし',
    installInfo: 'インストール情報を表示',
    addHome: 'ホーム画面に加',
    aboutBackground: 'バックグラウンドでの動作について',
    noiseType: 'ノイズタイプ',
    noisePapers: 'ノイズの論文リンクを表示',
    noiseReferences: 'ノイズに関する参考論文',
    beatOn: 'ビート ON',
    beatHelp: 'ビートの説明を表示',
    beatDesc: '左右で異なる音（バイノーラル）または等間隔のパルス（アイソクロニック）を流し、集中や休息を助ける機能です。',
    earphoneMode: 'イヤホン（バイノーラル）',
    speakerMode: 'スピーカー（アイソクロニック）',
    baseFreq: 'ベース周波数',
    currentBand: '現在の差分周波数の目安',
    footerNote: '医療効果を保証するものではありません。用途に合わせて慎重に使ってください。',
    minute: '分',
    second: '秒',
    iosStep1: '共有ボタン（四角に上矢印）をタップします。',
    iosStep2: '下にスクロールして「ホーム画面に加」をタップします。',
    iosStep3: '右上の「加」をタップします。',
    androidStep1: 'ブラウザの3点リーダーメニューをタップします。',
    androidStep2: '「アプリをインストール」または「ホーム画面に加」をタップします。',
    gotIt: '了解',
    close: '閉じる',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  te: {
    appName: 'Noise Maker',
    appTagline: 'సరళంగా, ప్రశాంతంగా, మీకు కావలసిన శబ్దమే.',
    install: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    installHint: 'హోమ్ స్క్రీన్‌కు చేర్చితే యాప్ త్వరగా తెరుచుకుంటుంది.',
    play: 'ప్లే',
    stop: 'ఆపు',
    addToHomeScreen: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    evidenceTitle: 'వివరణ మరియు పత్రాలు',
    platformTitle: 'PWA మరియు ప్లాట్‌ఫార్మ్ తేడాలు',
    simpleExplanationTitle: 'సంక్షిప్త వివరణ',
    volumeLabel: 'వాల్యూం',
    timerLabel: 'టైమర్',
    timerOff: 'ఆఫ్',
    installInfo: 'ఇన్‌స్టాలేషన్ సమాచారం చూపించు',
    addHome: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    aboutBackground: 'బ్యాక్‌గ్రౌండ్ ప్లేబ్యాక్ గురించి',
    noiseType: 'శబ్దం రకం',
    noisePapers: 'శబ్దం పత్రాలు చూపించు',
    noiseReferences: 'శబ్ద అధ్యయన సూచనలు',
    beatOn: 'బైనరల్ బీట్స్ ఆన్',
    beatHelp: 'బైనరల్ బీట్ సహాయం చూపించు',
    beatDesc: 'ప్రతి చెవికి కొద్దిగా భిన్నమైన టోన్లను పంపుతుంది, తద్వారా బీట్ తేడా మరింత స్పష్టంగా కనిపిస్తుంది.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'బేస్ ఫ్రీక్వెన్సీ',
    currentBand: 'ప్రస్తుత బీట్ బ్యాండ్',
    footerNote: 'వైద్యపరమైన క్లెయిమ్‌లు ఏవీ చేయబడలేదు. జాగ్రత్తగా ఉపయోగించండి మరియు మీ సందర్భానికి తగినట్లుగా అమర్చుకోండి.',
    minute: 'ని',
    second: 'సె',
    iosStep1: 'షోర్ బటన్ (పైకి బాణం ఉన్న చతురస్రం) నొక్కండి.',
    iosStep2: 'క్రిందికి స్క్రోల్ చేసి "హోమ్ స్క్రీన్‌కు చేర్చు" నొక్కండి.',
    iosStep3: 'పైన కుడివైపున ఉన్న "చేర్చు" నొక్కండి.',
    androidStep1: 'బ్రౌజర్‌లోని మూడు చుక్కల మెనూని నొక్కండి.',
    androidStep2: '"యాప్‌ను ఇన్‌స్టాల్ చేయి" లేదా "హోమ్ స్క్రీన్‌కు చేర్చు" నొక్కండి.',
    gotIt: 'అర్థమైంది',
    close: 'మూసివేయి',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  tr: {
    appName: 'Noise Maker',
    appTagline: 'Basit, sakin, sadece duymak istedigin ses.',
    install: 'Ana ekrana ekle',
    installHint: 'Ana ekrana eklemek daha hizli acilis saglar.',
    play: 'Oynat',
    stop: 'Durdur',
    addToHomeScreen: 'Ana ekrana ekle',
    evidenceTitle: 'Aciklama ve makaleler',
    platformTitle: 'PWA ve platform farklari',
    simpleExplanationTitle: 'Kisa aciklama',
    volumeLabel: 'Ses',
    timerLabel: 'Zamanlayici',
    timerOff: 'Kapali',
    installInfo: 'Kurulum bilgisini goster',
    addHome: 'Ana ekrana ekle',
    aboutBackground: 'Arka plan oynatma hakkinda',
    noiseType: 'Gurultu tipi',
    noisePapers: 'Gurultu makalelerini goster',
    noiseReferences: 'Gurultu calismalari referanslari',
    beatOn: 'Binaural vuruslar acik',
    beatHelp: 'Binaural vurus yardimini goster',
    beatDesc: 'Vurus farkinin daha net algilanabilmesi icin her kulaga biraz farkli tonlar gonderir.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Temel frekans',
    currentBand: 'Guncel vurus bandi',
    footerNote: 'Tibbi bir iddiada bulunulmamaktadir. Dikkatli kullanin ve baglaminiza gore uyarlayin.',
    minute: 'dk',
    second: 'sn',
    iosStep1: 'Paylaş düğmesine (yukarı oklu kare) dokunun.',
    iosStep2: 'Aşağı kaydırın ve "Ana Ekrana Ekle"ye dokunun.',
    iosStep3: 'Sağ üstteki "Ekle"ye dokunun.',
    androidStep1: 'Tarayıcıdaki üç nokta menüsüne dokunun.',
    androidStep2: '"Uygulamayı yükle" veya "Ana ekrana ekle"ye dokunun.',
    gotIt: 'Anladım',
    close: 'Kapat',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  ko: {
    appName: 'Noise Maker',
    appTagline: '간단하고 조용하게, 원하는 소리만.',
    install: '홈 화면에 추가',
    installHint: '홈 화면に추가하면 더 빠르게 실행됩니다.',
    play: '재생',
    stop: '정지',
    addToHomeScreen: '홈 화면に추가',
    evidenceTitle: '설명과 논문',
    platformTitle: 'PWA 및 플랫폼 차이',
    simpleExplanationTitle: '짧은 설명',
    volumeLabel: '볼륨',
    timerLabel: '타이머',
    timerOff: '끔',
    installInfo: '설치 정보 표시',
    addHome: '홈 화면に추가',
    aboutBackground: '백그라운드 재생에 대하여',
    noiseType: '노이즈 유형',
    noisePapers: '노이즈 논문 표시',
    noiseReferences: '노이즈 연구 참고 문서',
    beatOn: '바이노럴 비트 켜짐',
    beatHelp: '바이노럴 비트 도움말 표시',
    beatDesc: '양쪽 귀에 약간 다른 주파수를 흘려 차이 주파수를 더 명확하게 느낄 수 있게 하는 기능입니다.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: '베이스 주파수',
    currentBand: '현재 비트 밴드',
    footerNote: '의료적 효과를 보장하지 않습니다. 용도에 맞게 주의해서 사용하십시오.',
    minute: '분',
    second: '초',
    iosStep1: '공유 버튼(위쪽 화살표가 있는 사각형)을 누릅니다.',
    iosStep2: '아래로 스크롤하여 \'홈 화면에 추가\'를 누릅니다.',
    iosStep3: '오른쪽 상단의 \'추가\'를 누릅니다.',
    androidStep1: '브라우저에서 점 3개 메뉴를 누릅니다.',
    androidStep2: '\'앱 설치\' 또는 \'홈 화면에 추가\'를 누릅니다.',
    gotIt: '확인',
    close: '닫기',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  pa: {
    appName: 'Noise Maker',
    appTagline: 'ਸੌਖਾ, ਸ਼ਾਂਤ, ਸਿਰਫ ਉਹੀ ਆਵਾਜ਼ ਜੋ ਤੁਸੀਂ ਸੁਣਨਾ ਚਾਹੋ।',
    install: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    installHint: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜਨ ਨਾਲ ਐਪ ਜਲਦੀ ਖੁਲਦਾ ਹੈ।',
    play: 'ਚਲਾਓ',
    stop: 'ਰੋਕੋ',
    addToHomeScreen: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    evidenceTitle: 'ਵਿਆਖਿਆ ਅਤੇ ਲੇਖ',
    platformTitle: 'PWA ਅਤੇ ਪਲੇਟਫਾਰਮ ਅੰਤਰ',
    simpleExplanationTitle: 'ਛੋਟੀ ਵਿਆਖਿਆ',
    volumeLabel: 'ਆਵਾਜ਼',
    timerLabel: 'ਟਾਈਮਰ',
    timerOff: 'ਬੰਦ',
    installInfo: 'ਇੰਸਟਾਲੇਸ਼ਨ ਜਾਣਕਾਰੀ ਦਿਖਾਓ',
    addHome: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    aboutBackground: 'ਬੈਕਗ੍ਰਾਉਂਡ ਪਲੇਬੈਕ ਬਾਰੇ',
    noiseType: 'ਸ਼ੋਰ ਦੀ ਕਿਸਮ',
    noisePapers: 'ਸ਼ੋਰ ਲੇਖ ਦਿਖਾਓ',
    noiseReferences: 'ਸ਼ੋਰ ਅਧਿਐਨ ਦੇ ਹਵਾਲੇ',
    beatOn: 'ਬਾਇਨੋਰਲ ਬੀਟਸ ਚਾਲੂ',
    beatHelp: 'ਬਾਇਨੋਰਲ ਬੀਟ ਸਹਾਇਤਾ ਦਿਖਾਓ',
    beatDesc: 'ਹਰੇਕ ਕੰਨ ਵਿੱਚ ਥੋੜੇ ਵੱਖਰੇ ਟੋਨ ਭੇਜਦਾ ਹੈ ਤਾਂ ਜੋ ਬੀਟ ਦੇ ਅੰਤਰ ਨੂੰ ਹੋਰ ਸਪਸ਼ਟ ਰੂਪ ਵਿੱਚ سمجھਿਆ ਜਾ ਸਕੇ।',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'ਬੇਸ ਫ੍ਰੀਕੁਐਂਸੀ',
    currentBand: 'ਮੌਜੂਦਾ ਬੀਟ ਬੈਂਡ',
    footerNote: 'ਕੋਈ ਡਾਕਟਰੀ ਦਾਅਵਾ ਨਹੀਂ ਕੀਤਾ ਗਿਆ ਹੈ। ਇਸਦੀ ਸਾਵਧਾਨੀ ਨਾਲ ਵਰਤੋਂ ਕਰੋ ਅਤੇ ਆਪਣੇ ਸੰਦਰਭ ਅਨੁਸਾਰ ਢਾਲੋ।',
    minute: 'ਮਿੰਟ',
    second: 'ਸਕਿੰਟ',
    iosStep1: 'ਸ਼ੇਅਰ ਬਟਨ (ਉੱਪਰ ਤੀਰ ਵਾਲਾ ਵਰਗ) \'ਤੇ ਟੈਪ ਕਰੋ।',
    iosStep2: 'ਹੇਠਾਂ ਸਕ੍ਰੋਲ ਕਰੋ ਅਤੇ "ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ" ਤੇ ਟੈਪ ਕਰੋ।',
    iosStep3: 'ਉੱਪਰ ਸੱਜੇ ਪਾਸੇ "ਜੋੜੋ" ਤੇ ਟੈਪ ਕਰੋ।',
    androidStep1: 'ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਤਿੰਨ-ਬਿੰਦੂ ਮੀਨੂ \'ਤੇ ਟੈਪ ਕਰੋ।',
    androidStep2: '"ਐਪ ਇੰਸਟਾਲ ਕਰੋ" ਜਾਂ "ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ" ਤੇ ਟੈਪ ਕਰੋ।',
    gotIt: 'ਸਮਝ ਗਏ',
    close: 'ਬੰਦ ਕਰੋ',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  ta: {
    appName: 'Noise Maker',
    appTagline: 'எளிதாக, அமைதியாக, உங்களுக்கு வேண்டிய ஒலி மட்டும்.',
    install: 'முதற்பக்கத்தில் சேர்க்க',
    installHint: 'முதற்பக்கத்தில் சேர்த்தால் விரைவாக திறக்கும்.',
    play: 'இயக்கு',
    stop: 'நிறுத்து',
    addToHomeScreen: 'முதற்பக்கத்தில் சேர்க்க',
    evidenceTitle: 'விளக்கம் மற்றும் ஆய்வுகள்',
    platformTitle: 'PWA மற்றும் தளம் வேறுபாடுகள்',
    simpleExplanationTitle: 'சுருக்கமான விளக்கம்',
    volumeLabel: 'ஒலி அளவு',
    timerLabel: 'டைமர்',
    timerOff: 'ஆஃப்',
    installInfo: 'நிறுவல் தகவலைக் காட்டு',
    addHome: 'முதற்பக்கத்தில் சேர்க்க',
    aboutBackground: 'பின்னணி இயக்கம் பற்றி',
    noiseType: 'ஒலி வகை',
    noisePapers: 'ஒலி ஆய்வுகளைக் காட்டு',
    noiseReferences: 'ஒலி ஆய்வுகளின் குறிப்புகள்',
    beatOn: 'பைனரல் பீட்ஸ் ஆன்',
    beatHelp: 'பைனரல் பீட் உதவியைக் காட்டு',
    beatDesc: 'ஒவ்வொரு காதுக்கும் சற்று வித்தியாசமான ஒலிகளை அனுப்புகிறது, இதனால் பீட் வித்தியாசத்தை இன்னும் தெளிவாக உணர முடியும்.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'அடிப்படை அதிர்வெண்',
    currentBand: 'தற்போதைய பீட் பேண்ட்',
    footerNote: 'மருத்துவ ரீதியான உரிமைகோரல்கள் எதுவும் செய்யப்படவில்லை. எச்சரிக்கையுடன் பயன்படுத்தவும்.',
    minute: 'நி',
    second: 'வி',
    iosStep1: 'பகிர் பொத்தானைத் (மேல் அம்புக்குறியுடன் கூடிய சதுரம்) தட்டவும்.',
    iosStep2: 'கீழே உருட்டி "முதற்பக்கத்தில் சேர்க்க" என்பதைத் தட்டவும்.',
    iosStep3: 'மேல் வலதுபுறத்தில் உள்ள "சேர்" என்பதைத் தட்டவும்.',
    androidStep1: 'உலாவியில் உள்ள மூன்று புள்ளி மெனுவைத் தட்டவும்.',
    androidStep2: '"பயன்பாட்டை நிறுவு" அல்லது "முதற்பக்கத்தில் சேர்க்க" என்பதைத் தட்டவும்.',
    gotIt: 'புரிந்தது',
    close: 'மூடு',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  jv: {
    appName: 'Noise Maker',
    appTagline: 'Prasaja lan anteng, mung swara sing arep kok rungokke.',
    install: 'Tambahna menyang layar ngarep',
    installHint: 'Yen ditambah menyang layar ngarep, mbukak app luwih cepet.',
    play: 'Puter',
    stop: 'Mandheg',
    addToHomeScreen: 'Tambahna menyang layar ngarep',
    evidenceTitle: 'Panjelasan lan artikel',
    platformTitle: 'PWA lan bedane platform',
    simpleExplanationTitle: 'Panjelasan cekak',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Mati',
    installInfo: 'Tampilake info instalasi',
    addHome: 'Tambah menyang layar ngarep',
    aboutBackground: 'Babagan puter ing mburi',
    noiseType: 'Tipe swara',
    noisePapers: 'Tampilake artikel swara',
    noiseReferences: 'Referensi kanggo studi swara',
    beatOn: 'Ketukan binaural urip',
    beatHelp: 'Tampilake pitulung ketukan binaural',
    beatDesc: 'Ngirim nada sing rada beda menyang saben kuping supaya bedane ketukan bisa dirasakake luwih cetha.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Frekuensi dasar',
    currentBand: 'Band ketukan saiki',
    footerNote: 'Ora ana klaim medis. Gunakake kanthi teliti lan cocogake karo konteksmu.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tutul tombol Dum (kothak nganggo panah munggah).',
    iosStep2: 'Gulung mudhun lan tutul "Tambahna menyang layar ngarep".',
    iosStep3: 'Tutul "Tambah" ing sisih tengen ndhuwur.',
    androidStep1: 'Tutul menu telu titik ing browser.',
    androidStep2: 'Tutul "Pasang aplikasi" utawa "Tambahna menyang layar ngarep".',
    gotIt: 'Ngerti',
    close: 'Tutup',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  it: {
    appName: 'Noise Maker',
    appTagline: 'Semplice e tranquillo, solo il suono che vuoi ascoltare.',
    install: 'Aggiungi alla schermata Home',
    installHint: 'Aggiungendola alla Home, si avvia piu rapidamente.',
    play: 'Riproduci',
    stop: 'Ferma',
    addToHomeScreen: 'Aggiungi alla schermata Home',
    evidenceTitle: 'Spiegazione e studi',
    platformTitle: 'PWA e differenze di piattaforma',
    simpleExplanationTitle: 'Spiegazione breve',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Off',
    installInfo: 'Mostra info installazione',
    addHome: 'Aggiungi alla schermata iniziale',
    aboutBackground: 'Riproduzione in background',
    noiseType: 'Tipo di rumore',
    noisePapers: 'Mostra studi sul rumore',
    noiseReferences: 'Riferimenti per studi sul rumore',
    beatOn: 'Battiti binaurali attivi',
    beatHelp: 'Mostra aiuto battiti binaurali',
    beatDesc: 'Invia toni leggermente diversi a ciascun orecchio in modo che la differenza di battito sia percepita piu chiaramente.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Frequenza base',
    currentBand: 'Banda di battito attuale',
    footerNote: 'Non si effettuano affermazioni mediche. Usalo con cautela e adattalo al tuo contesto.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tocca il pulsante Condividi (quadrato con freccia verso l\'alto).',
    iosStep2: 'Scorri verso il basso e tocca "Aggiungi alla schermata Home".',
    iosStep3: 'Tocca "Aggiungi" in alto a destra.',
    androidStep1: 'Tocca il menu con i tre puntini nel browser.',
    androidStep2: 'Tocca "Installa app" o "Aggiungi alla schermata Home".',
    gotIt: 'Ho capito',
    close: 'Chiudi',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  fr: {
    appName: 'Noise Maker',
    appTagline: 'Simple et calme, uniquement le son que vous voulez.',
    install: 'Ajouter a l ecran d accueil',
    installHint: 'L ajout a l ecran d accueil accelere le lancement.',
    play: 'Lire',
    stop: 'Arreter',
    addToHomeScreen: 'Ajouter a l ecran d accueil',
    evidenceTitle: 'Explication et etudes',
    platformTitle: 'PWA et differences de plateforme',
    simpleExplanationTitle: 'Explication courte',
    volumeLabel: 'Volume',
    timerLabel: 'Minuteur',
    timerOff: 'Off',
    installInfo: 'Afficher les infos d installation',
    addHome: 'Ajouter a l ecran d accueil',
    aboutBackground: 'A propos de la lecture en arriere-plan',
    noiseType: 'Type de bruit',
    noisePapers: 'Afficher les etudes sur le bruit',
    noiseReferences: 'References pour les etudes sur le bruit',
    beatOn: 'Battements binauraux actifs',
    beatHelp: 'Afficher l aide sur les battements',
    beatDesc: 'Envoie des sons legerement differents a chaque oreille pour que la difference de battement soit percue plus clairement.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Frequence de base',
    currentBand: 'Bande de battement actuelle',
    footerNote: 'Aucune reclamation medicale n est faite. Utilisez-le avec prudence et adaptez-le a votre contexte.',
    minute: 'm',
    second: 's',
    iosStep1: 'Appuyez sur le bouton Partager (carré với une flèche vers le haut).',
    iosStep2: 'Faites défiler vers le bas et appuyez sur « Sur l\'écran d\'accueil ».',
    iosStep3: 'Appuyez sur « Ajouter » en haut à droite.',
    androidStep1: 'Appuyez sur le menu à trois points dans le navigateur.',
    androidStep2: 'Appuyez sur « Installer l\'application » ou « Sur l\'écran d\'accueil ».',
    gotIt: 'J\'ai compris',
    close: 'Fermer',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  de: {
    appName: 'Noise Maker',
    appTagline: 'Einfach und ruhig, nur der Klang, den du horen willst.',
    install: 'Zum Startbildschirm hinzufugen',
    installHint: 'Mit Startbildschirm startet die App schneller.',
    play: 'Abspielen',
    stop: 'Stoppen',
    addToHomeScreen: 'Zum Startbildschirm hinzufugen',
    evidenceTitle: 'Erklarung und Studien',
    platformTitle: 'PWA und Plattformunterschiede',
    simpleExplanationTitle: 'Kurze Erklarung',
    volumeLabel: 'Lautstarke',
    timerLabel: 'Timer',
    timerOff: 'Aus',
    installInfo: 'Installationsinfo anzeigen',
    addHome: 'Zum Startbildschirm hinzufugen',
    aboutBackground: 'Uber Hintergrundwiedergabe',
    noiseType: 'Rauschtyp',
    noisePapers: 'Rauschstudien anzeigen',
    noiseReferences: 'Referenzen fur Rauschstudien',
    beatOn: 'Binaurale Beats an',
    beatHelp: 'Hilfe zu binauralen Beats',
    beatDesc: 'Sendet leicht unterschiedliche Tone an jedes Ohr, damit der Beat-Unterschied deutlicher wahrgenommen werden kann.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Basisfrequenz',
    currentBand: 'Aktuelles Beat-Band',
    footerNote: 'Es werden keine medizinischen Anspruche erhoben. Vorsichtig verwenden und an den Kontext anpassen.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tippen Sie auf die Teilen-Schaltfläche (Quadrat mit Pfeil nach oben).',
    iosStep2: 'Scrollen Sie nach unten und tippen Sie auf „Zum Home-Bildschirm“.',
    iosStep3: 'Tippen Sie oben rechts auf „Hinzufügen“.',
    androidStep1: 'Tippen Sie im Browser auf das Drei-Punkte-Menü.',
    androidStep2: 'Tippen Sie auf „App installieren“ oder „Zum Home-Bildschirm hinzufügen“.',
    gotIt: 'Verstanden',
    close: 'Schließen',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  },
  id: {
    appName: 'Noise Maker',
    appTagline: 'Sederhana dan tenang, hanya suara yang ingin kamu dengar.',
    install: 'Tambahkan ke layar utama',
    installHint: 'Menambahkan ke layar utama membuat aplikasi lebih cepat dibuka.',
    play: 'Putar',
    stop: 'Hentikan',
    addToHomeScreen: 'Tambahkan ke layar utama',
    evidenceTitle: 'Penjelasan dan studi',
    platformTitle: 'PWA dan perbedaan platform',
    simpleExplanationTitle: 'Penjelasan singkat',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Mati',
    installInfo: 'Tampilkan info instalasi',
    addHome: 'Tambahkan ke layar utama',
    aboutBackground: 'Tentang pemutaran latar belakang',
    noiseType: 'Tipe kebisingan',
    noisePapers: 'Tampilkan studi kebisingan',
    noiseReferences: 'Referensi untuk studi kebisingan',
    beatOn: 'Ketukan binaural aktif',
    beatHelp: 'Tampilkan bantuan ketukan binaural',
    beatDesc: 'Mengirimkan nada yang sedikit berbeda ke mỗi tai để sự khác biệt nhịp được cảm nhận rõ ràng hơn.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Frekuensi dasar',
    currentBand: 'Pita ketukan saat ini',
    footerNote: 'Tidak ada klaim medis yang dibuat. Gunakan dengan hati-hati dan sesuaikan dengan konteks Anda.',
    minute: 'm',
    second: 's',
    iosStep1: 'Ketuk tombol Bagikan (persegi dengan panah ke atas).',
    iosStep2: 'Gulir ke bawah và ketuk "Tambahkan ke Layar Utama".',
    iosStep3: 'Ketuk "Tambah" di kanan atas.',
    androidStep1: 'Ketuk menu tiga titik di browser.',
    androidStep2: 'Ketuk "Instal aplikasi" hoặc "Tambahkan ke layar utama".',
    gotIt: 'Mengerti',
    close: 'Tutup',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off'
  }
};

export function resolveLocalizedText(text: LocalizedText, locale: Locale): string {
  return text[locale] ?? text.en ?? text.ja;
}

function resolveLocalizedList(list: LocalizedList, locale: Locale): string[] {
  return list[locale] ?? list.en ?? list.ja;
}

export const noiseTypes: Array<{
  key: NoiseType;
  label: LocalizedText;
  short: LocalizedText;
}> = [
  { 
    key: 'white', 
    label: { 
      ja: 'ホワイト', en: 'White', 'zh-Hans': '白噪音', es: 'Blanco', ko: '화이트', fr: 'Blanc', de: 'Weiß',
      hi: 'सफ़ेद', bn: 'সাদা', pt: 'Branco', ru: 'Белый', yue: '白噪音', vi: 'Trắng', mr: 'पांढरा', te: 'తెలుపు', tr: 'Beyaz', pa: 'ਚਿੱਟਾ', ta: 'வெள்ளை', jv: 'Putih', it: 'Bianco', id: 'Putih'
    }, 
    short: { 
      ja: '環境音を目立ちにくくして、作業や休憩の切り替えに使われることがあります。', 
      en: 'Often used to mask background sounds and support task or rest transitions.',
      'zh-Hans': '通常用于遮蔽背景噪音，支持工作或休息的切换。',
      es: 'A menudo se usa para enmascarar sonidos de fondo y apoyar transiciones de tareas.',
      ko: '주변 소음을 차단하고 작업이나 휴식의 전환을 돕는 데 사용됩니다.',
      fr: 'Souvent utilisé pour masquer les bruits de fond et faciliter les transitions.',
      de: 'Wird oft verwendet, um Hintergrundgeräusche zu maskieren.',
      hi: 'अक्सर पृष्ठभूमि की आवाज़ों को छिपाने और कार्य या आराम के संक्रमण का समर्थन करने के लिए उपयोग किया जाता है।',
      bn: 'প্রায়শই পটভূমির শব্দ মাস্ক করতে এবং কাজ বা বিশ্রামের ট্রানজিশন সমর্থন করতে ব্যবহৃত হয়।',
      pt: 'Frequentemente usado para mascarar sons de fundo e apoiar transições de tarefas ou descanso.',
      ru: 'Часто используется для маскировки фоновых звуков и поддержки переходов между задачами или отдыхом.',
      yue: '通常用於遮蔽背景噪音，支持工作或休息嘅切換。',
      vi: 'Thường được sử dụng để che bớt âm thanh nền và hỗ trợ chuyển đổi công việc hoặc nghỉ ngơi.',
      mr: 'बऱ्याचदा पार्श्वभूमीचे आवाज मास्क करण्यासाठी आणि कार्य किंवा विश्रांती संक्रमणास समर्थन देण्यासाठी वापरले जाते.',
      te: 'తరచుగా నేపథ్య శబ్దాలను దాచడానికి మరియు పని లేదా విశ్రాంతి పరివర్తనలకు మద్దతు ఇవ్వడానికి ఉపయోగిస్తారు.',
      tr: 'Genellikle arka plan seslerini maskelemek ve görev veya dinlenme geçişlerini desteklemek için kullanılır.',
      pa: 'ਅਕਸਰ ਪਿਛੋਕੜ ਦੀਆਂ ਆਵਾਜ਼ਾਂ ਨੂੰ ਲੁਕਾਉਣ ਅਤੇ ਕੰਮ ਜਾਂ ਆਰਾਮ ਦੇ ਸੰਕਰਮਣ ਦਾ ਸਮਰਥਨ ਕਰਨ ਲਈ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।',
      ta: 'பின்னணி ஒலிகளை மறைக்கவும், வேலை அல்லது ஓய்வு மாற்றங்களுக்கு ஆதரவளிக்கவும் பெரும்பாலும் பயன்படுத்தப்படுகிறது.',
      jv: 'Asring digunake kanggo nutupi swara latar mburi lan ndhukung transisi tugas utawa istirahat.',
      it: 'Spesso utilizzato per mascherare i suoni di sottofondo e supportare le transizioni tra attività o riposo.',
      id: 'Sering digunakan untuk menyamarkan suara latar belakang dan mendukung transisi tugas atau istirahat.'
    } 
  },
  { 
    key: 'pink', 
    label: { 
      ja: 'ピンク', en: 'Pink', 'zh-Hans': '粉红噪音', es: 'Rosa', ko: '핑크', fr: 'Rose', de: 'Rosa',
      hi: 'गुलाबी', bn: 'গোলাপী', pt: 'Rosa', ru: 'Розовый', yue: '粉紅噪音', vi: 'Hồng', mr: 'गुलाबी', te: 'గులాబీ', tr: 'Pembe', pa: 'ਗੁਲਾਬੀ', ta: 'இளஞ்சிவப்பு', jv: 'Abang enom', it: 'Rosa', id: 'Merah muda'
    }, 
    short: { 
      ja: '就寝前に落ち着きやすいと感じる人がいます。睡眠への効果は研究でも個人差があります。', 
      en: 'Some people find it easier to settle before sleep. Sleep effects vary across studies.',
      'zh-Hans': '有些人觉得睡前更容易安静。睡眠效果在研究中因人而异。',
      es: 'A algunas personas les resulta más fácil calmarse antes de dormir.',
      ko: '취침 전에 마음을 진정시키는 데 도움이 될 수 있습니다. 수면 효과는 개인차가 있습니다.',
      fr: 'Certaines personnes le trouvent apaisant avant de dormir.',
      de: 'Manche finden es vor dem Schlafengehen beruhigend.',
      hi: 'कुछ लोगों को सोने से पहले शांत होना आसान लगता है। नींद पर এর प्रभाव अध्ययनों में भिन्न होते हैं।',
      bn: 'কিছু মানুষ ঘুমানোর আগে শান্ত হওয়া সহজ মনে করেন। ঘুমের উপর এর প্রভাব বিভিন্ন গবেষণায় ভিন্ন ভিন্ন হয়।',
      pt: 'Algumas pessoas acham mais fácil relaxar antes de dormir. Os efeitos no sono variam entre los estudos.',
      ru: 'Некоторым людям легче успокоиться перед сном. Эффект на сон варьируется в разных исследованиях.',
      yue: '有啲人覺得睡前更容易安靜。睡眠效果喺研究中因人而異。',
      vi: 'Một số người cảm thấy dễ dàng bình tĩnh hơn trước khi ngủ. Hiệu quả giấc ngủ thay đổi tùy theo nghiên cứu.',
      mr: 'काही लोकांना झोपण्यापूर्वी शांत होणे सोपे वाटते. झोपेवर होणारे परिणाम अभ्यासानुसार बदलतात.',
      te: 'కొంతమంది నిద్రపోయే ముందు ప్రశాంతంగా ఉండటం సులభం అని భావిస్తారు. నిద్రపై దీని ప్రభావాలు అధ్యయనాలలో మారుతుంటాయి.',
      tr: 'Bazı insanlar uykudan önce sakinleşmeyi daha kolay bulur. Uyku etkileri çalışmalar arasında farklılık gösterir.',
      pa: 'ਕੁਝ ਲੋਕਾਂ ਨੂੰ ਸੌਣ ਤੋਂ ਪਹਿਲਾਂ ਸ਼ਾਂਤ ਹੋਣਾ ਸੌਖਾ ਲੱਗਦਾ ਹੈ। ਨੀਂਦ \'ਤੇ ਇਸਦੇ ਪ੍ਰਭਾਵ ਵੱਖ-ਵੱਖ ਅਧਿਐਨਾਂ ਵਿੱਚ ਵੱਖਰੇ ਹੁੰਦੇ ਹਨ।',
      ta: 'சிலர் தூங்குவதற்கு முன் அமைதியடைவது எளிது என்று கருதுகின்றனர். தூக்கத்தின் மீதான இதன் விளைவுகள் ஆய்வுகளில் மாறுபடும்.',
      jv: 'Sawetara wong ngrasa luwih gampang tenang sadurunge turu. Efek turu beda-beda ing saben panaliten.',
      it: 'Alcune persone trovano più facile calmarsi prima di dormire. Gli effetti sul sonno variano a seconda degli studi.',
      id: 'Beberapa người merasa lebih mudah untuk tenang sebelum tidur. Efek tidur bervariasi di berbagai penelitian.'
    } 
  },
  { 
    key: 'brown', 
    label: { 
      ja: 'ブラウン', en: 'Brown', 'zh-Hans': '褐噪音', es: 'Marrón', ko: '브라운', fr: 'Brun', de: 'Braun',
      hi: 'भूरा', bn: 'बादামী', pt: 'Castanho', ru: 'Коричневый', yue: '褐噪音', vi: 'Nâu', mr: 'तपकिरी', te: 'గోధుమ', tr: 'Kahverengi', pa: 'ਭੂਰਾ', ta: 'பழுப்பு', jv: 'Coklat', it: 'Marrone', id: 'Cokelat'
    }, 
    short: { 
      ja: '低めで包まれる感覚があり、リラックス目的で選ばれることがあります。', 
      en: 'Its deeper tone can feel enveloping, so some listeners choose it for relaxation.',
      'zh-Hans': '低沉的包围感，常被用于放松目的。',
      es: 'Su tono más profundo puede sentirse envolvente, ideal para la relajación.',
      ko: '낮은 톤으로 감싸이는 느낌이 있어 휴식을 위해 선택되기도 합니다.',
      fr: 'Son ton plus profond peut sembler enveloppant, idéal pour la relaxation.',
      de: 'Sein tieferer Ton kann sich einhüllend anfühlen, ideal zur Entspannung.',
      hi: 'इसकी गहरी ध्वनि घेरने वाली महसूस हो सकती है, इसलिए कुछ सुनने वाले इसे विश्राम के लिए चुनते हैं।',
      bn: 'এর গভীর সুর আপনাকে ঘিরে রাখার অনুভূতি দিতে পারে, তাই কিছু শ্রোতা এটি বিশ্রামের জন্য বেছে নেন।',
      pt: 'Seu tom mais profundo pode parecer envolvente, por isso alguns ouvintes o escolhem para relaxar.',
      ru: 'Его более глубокий тон может казаться обволакивающим, поэтому некоторые слушатели выбирают его для расслабления.',
      yue: '低沉嘅包圍感，常用於放鬆目的。',
      vi: 'Tông màu sâu hơn của nó có thể tạo cảm giác bao bọc, vì vậy một số người nghe chọn nó để thư giãn.',
      mr: 'याचा सखोल सूर वेढून घेणारा वाटू शकतो, म्हणून काही श्रोते विश्रांतीसाठी याची निवड करतात.',
      te: 'దీని లోతైన టోన్ ఆవరించినట్లు అనిపిస్తుంది, కాబట్టి కొంతమంది శ్రోతలు విశ్రాంతి కోసం దీనిని ఎంచుకుంటారు.',
      tr: 'Daha derin tonu çevreleyici hissettirebilir, bu nedenle bazı dinleyiciler bunu rahatlama için seçer.',
      pa: 'ਇਸਦਾ ਡੂੰਘਾ ਸੁਰ ਘੇਰਨ ਵਾਲਾ ਮਹਿਸੂਸ ਹੋ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਕੁਝ ਸੁਣਨ ਵਾਲੇ ਇਸਨੂੰ ਆਰਾਮ ਲਈ ਚੁਣਦੇ ਹਨ।',
      ta: 'இதன் ஆழமான ஒலி சூழ்ந்திருப்பது போன்ற உணர்வைத் தரும், எனவே சில கேட்பவர்கள் இதை ஓய்வெடுக்கத் தேர்வு செய்கிறார்கள்।',
      jv: 'Nada sing luwih jero bisa krasa ngrangkul, mula sawetara wong milih iki kanggo relaksasi.',
      it: 'Il suo tono più profondo può sembrare avvolgente, quindi alcuni ascoltatori lo scelgono per il rilassamento.',
      id: 'Nadanya yang lebih dalam bisa terasa menyelimuti, sehingga beberapa pendengar memilihnya untuk relaksasi.'
    } 
  },
  { 
    key: 'blue', 
    label: { 
      ja: 'ブルー', en: 'Blue', 'zh-Hans': '蓝噪音', es: 'Azul', ko: '블루', fr: 'Bleu', de: 'Blau',
      hi: 'नीला', bn: 'নীল', pt: 'Azul', ru: 'Голубой', yue: '藍噪音', vi: 'Xanh dương', mr: 'निळा', te: 'నీలం', tr: 'Mavi', pa: 'ਨੀਲਾ', ta: 'நீலம்', jv: 'Biru', it: 'Blu', id: 'Biru'
    }, 
    short: { 
      ja: '気分を切り替えたい場面で、短時間の集中スイッチとして使う人もいます。', 
      en: 'Sometimes used as a short focus reset when people want a quick mental shift.',
      'zh-Hans': '在需要转换心情时，有人将其作为短时间集中的开关。',
      es: 'A veces se usa como un breve reinicio de enfoque para un cambio mental rápido.',
      ko: '기분 전환이 필요한 상황에서 단시간 집중을 위한 스위치로 사용되기도 합니다.',
      fr: 'Parfois utilisé pour réinitialiser la concentration rapidement.',
      de: 'Wird manchmal für einen kurzen Fokus-Reset verwendet.',
      hi: 'कभी-कभी एक संक्षिप्त ध्यान रीसेट के रूप में उपयोग किया जाता है जब लोग एक त्वरित मानसिक बदलाव चाहते हैं।',
      bn: 'কখনও কখনও একটি সংক্ষিপ্ত ফোকাস রিসেট হিসাবে ব্যবহৃত হয় যখন লোকেরা দ্রুত মানসিক পরিবর্তন চান।',
      pt: 'Às vezes usado como um breve reinício de foco quando as pessoas querem uma mudança mental rápida.',
      ru: 'Иногда используется как кратковременная перезагрузка внимания, когда требуется быстрая смена психического состояния.',
      yue: '喺需要轉換心情時，有人將佢作為短時間集中嘅開關。',
      vi: 'Đôi khi được sử dụng như một lần đặt lại sự tập trung ngắn khi mọi người muốn có một sự thay đổi tinh thần nhanh chóng.',
      mr: 'जेव्हा लोकांना त्वरित मानसिक बदल हवा असतो तेव्हा कधीकधी संक्षिप्त फोकस रीसेट म्हणून वापरले जाते.',
      te: 'ప్రజలు త్వరిత మానసిక మార్పును కోరుకున్నప్పుడు కొన్నిసార్లు చిన్న ఫోకస్ రీసెట్‌గా ఉపయోగించబడుతుంది.',
      tr: 'İnsanlar hızlı bir zihinsel değişim istediğinde bazen kısa bir odaklanma sıfırlaması olarak kullanılır.',
      pa: 'ਕਦੇ-ਕਦੇ ਇੱਕ ਸੰਖੇਪ ਫੋਕਸ ਰੀਸੈਟ ਵਜੋਂ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ ਜਦੋਂ ਲੋਕ ਇੱਕ ਤੇਜ਼ ਮਾਨਸਿਕ ਤਬਦੀਲੀ ਚਾਹੁੰਦੇ ਹਨ।',
      ta: 'மக்கள் விரைவான மன மாற்றத்தை விரும்பும்போது சில நேரங்களில் குறுகிய கவனம் மீட்டமைப்பாகப் பயன்படுத்தப்படுகிறது.',
      jv: 'Sok-sok digunakake minangka reset fokus cendhak nalika wong pengin owah-owahan mental sing cepet.',
      it: 'A volte usato come breve reset della messa a fuoco quando si desidera un rapido cambiamento mentale.',
      id: 'Terkadang digunakan sebagai reset fokus singkat ketika orang menginginkan perubahan mental yang cepat.'
    } 
  },
  { 
    key: 'violet', 
    label: { 
      ja: 'ヴァイオレット', en: 'Violet', 'zh-Hans': '紫噪音', es: 'Violeta', ko: '바이올렛', fr: 'Violet', de: 'Violett',
      hi: 'बैंगनी', bn: 'বেগুনী', pt: 'Violeta', ru: 'Фиолетовый', yue: '紫噪音', vi: 'Tím', mr: 'जांभळा', te: 'వైలెట్', tr: 'Mor', pa: 'ਬੈਂਗਣੀ', ta: 'ஊதா', jv: 'Ungu', it: 'Violetto', id: 'Violet'
    }, 
    short: { 
      ja: '高めの刺激で注意を向けやすいと感じる人がいますが、長時間は疲れやすいことがあります。', 
      en: 'Some listeners feel more alert with it, though long sessions can be fatiguing.',
      'zh-Hans': '高频率刺激让人更容易集中注意力，但长时间使用可能会疲劳。',
      es: 'Algunos oyentes se sienten más alerta, aunque sesiones largas pueden fatigar.',
      ko: '높은 자극으로 주의를 끌기 쉽지만, 장시간 사용 시 피로할 수 있습니다.',
      fr: 'Certaines personnes le trouvent apaisant avant de dormir.',
      de: 'Manche fühlen sich wacher, aber lange Sitzungen können ermüdend sein.',
      hi: 'कुछ सुनने वाले इससे अधिक सतर्क महसूस करते हैं, हालांकि लंबे सत्र थकाने वाले हो सकते हैं।',
      bn: 'কিছু শ্রোতা এটি দিয়ে আরও सतर्क বোধ করেন, যদিও দীর্ঘ সেশন ক্লান্তিকর হতে পারে।',
      pt: 'Alguns ouvintes sentem-se mais alertas com ele, embora sessões longas possam ser cansativas.',
      ru: 'Некоторые слушатели чувствуют себя бодрее с ним, хотя длительные сеансы могут утомлять.',
      yue: '高頻率刺激令人更容易集中注意力，但長時間使用可能會疲勞。',
      vi: 'Một số người nghe cảm thấy tỉnh táo hơn với nó, mặc dù các phiên kéo dài có thể gây mệt mỏi.',
      mr: 'काही श्रोत्यांना यामुळे अधिक सतर्क वाटते, जरी दीर्घ सत्र थकवणारे असू शकतात.',
      te: 'కొంతమంది శ్రోతలు దీనితో మరింత అప్రమత్తంగా ఉన్నట్లు భావిస్తారు, అయితే సుదీర్ఘ సెషన్లు అలసటను కలిగిస్తాయి.',
      tr: 'Bazı dinleyiciler bununla daha uyanık hisseder, ancak uzun seanslar yorucu olabilir.',
      pa: 'ਕੁਝ ਸੁਣਨ ਵਾਲੇ ਇਸ ਨਾਲ ਵਧੇਰੇ ਸੁਚੇਤ ਮਹਿਸੂਸ ਕਰਦੇ ਹਨ, ਹਾਲਾਂਕਿ ਲੰਬੇ ਸੈਸ਼ਨ ਥਕਾਊ ਹੋ ਸਕਦੇ ਹਨ।',
      ta: 'சில கேட்பவர்கள் இதனுடன் அதிக விழிப்புடன் இருப்பதாக உணர்கிறார்கள், இருப்பினும் நீண்ட அமர்வுகள் சோர்வாக இருக்கலாம்.',
      jv: 'Sawetara wong ngrasa luwih waspada karo iki, sanajan sesi sing suwe bisa nggawe kesel.',
      it: 'Alcuni ascoltatori si sentono più vigili con esso, anche se sessioni lunghe possono essere affaticanti.',
      id: 'Beberapa pendengar merasa lebih waspada dengannya, meskipun sesi yang lama bisa melelahkan.'
    } 
  },
  {
    key: 'off',
    label: { ja: 'オフ', en: 'Off' },
    short: { ja: 'ノイズを停止します。', en: 'Turn off noise.' }
  }
];

export const binauralBands: Array<{
  key: string;
  min: number;
  max: number;
  symbol: string;
  label: LocalizedText;
  reading: LocalizedText;
  effect: LocalizedText;
}> = [
  {
    key: 'delta',
    min: 0.5,
    max: 4,
    symbol: 'Δ',
    label: { ja: 'デルタ', en: 'Delta' },
    reading: { ja: '0.5-4Hz', en: '0.5-4Hz' },
    effect: {
      ja: '深い休息モードに寄せたいときの目安です。夜の静かな時間に合わせやすい帯域です。',
      en: 'A common target when aiming for a deeper rest mood, especially in quiet night sessions.'
    }
  },
  {
    key: 'theta',
    min: 4,
    max: 8,
    symbol: 'θ',
    label: { ja: 'シータ', en: 'Theta' },
    reading: { ja: '4-8Hz', en: '4-8Hz' },
    effect: {
      ja: '落ち着きや内省の感覚と結びつけられることがあります。体感は人によって大きく変わります。',
      en: 'Sometimes linked to calm or inward attention, with large person-to-person variation.'
    }
  },
  {
    key: 'alpha',
    min: 8,
    max: 13,
    symbol: 'α',
    label: { ja: 'アルファ', en: 'Alpha' },
    reading: { ja: '8-13Hz', en: '8-13Hz' },
    effect: {
      ja: 'リラックスしつつ作業したいときに選ばれやすい、バランス型の帯域です。',
      en: 'A balanced range often chosen for relaxed but awake sessions.'
    }
  },
  {
    key: 'beta',
    min: 13,
    max: 30,
    symbol: 'β',
    label: { ja: 'ベータ', en: 'Beta' },
    reading: { ja: '13-30Hz', en: '13-30Hz' },
    effect: {
      ja: '注意や課題集中に関連づけられる帯域です。人によっては刺激が強すぎる場合があります。',
      en: 'Often associated with attention and task focus, though it may feel overstimulating.'
    }
  },
  {
    key: 'gamma',
    min: 30,
    max: 40,
    symbol: 'γ',
    label: { ja: 'ガンマ', en: 'Gamma' },
    reading: { ja: '30-40Hz', en: '30-40Hz' },
    effect: {
      ja: '切り替えや短時間の高集中に向けた高めの帯域です。刺激が強く感じる場合があります。',
      en: 'A higher band often used for short, high-focus pushes; it can feel intense.'
    }
  }
];

export const presets: Preset[] = [
  {
    key: 'focus',
    label: { ja: '1. 深い集中 (Focus)', en: '1. Deep Focus' },
    description: { 
      ja: 'プログラミングや執筆など、雑念を消して没入したい時に。ブラウンノイズとベータ波で思考を活性化させます。', 
      en: 'For coding or writing. Brown noise and Beta waves to mask distractions and activate thinking.' 
    },
    noiseType: 'brown',
    beatBand: 'beta',
    baseFrequency: 440
  },
  {
    key: 'creative',
    label: { ja: '2. 創造的思考 (Creative)', en: '2. Creative Flow' },
    description: { 
      ja: '企画、設計、読書など、リラックスしつつ意識を広げたい時に。ピンクノイズとアルファ波で脳をフラットに保ちます。', 
      en: 'For planning or reading. Pink noise and Alpha waves for a relaxed yet expansive mindset.' 
    },
    noiseType: 'pink',
    beatBand: 'alpha',
    baseFrequency: 528
  },
  {
    key: 'study',
    label: { ja: '3. 短期集中 (Study)', en: '3. Quick Study' },
    description: { 
      ja: '試験前の詰め込みなど、短時間で情報を処理したい時に。ホワイトノイズとガンマ波で高い覚醒状態を作ります。', 
      en: 'For pre-exam pushes. White noise and Gamma waves to boost processing speed and alertness.' 
    },
    noiseType: 'white',
    beatBand: 'gamma',
    baseFrequency: 741
  },
  {
    key: 'meditation',
    label: { ja: '4. 瞑想・休息 (Meditate)', en: '4. Meditation' },
    description: { 
      ja: '休憩時間や、心を落ち着かせたい時に。ノイズをオフにし、396Hzのベースとシータ波で深い瞑想へ誘導します。', 
      en: 'To calm the mind. Noise off, 396Hz base and Theta waves to support deep reflection and stability.' 
    },
    noiseType: 'off',
    beatBand: 'theta',
    baseFrequency: 396
  },
  {
    key: 'sleep',
    label: { ja: '5. 入眠 (Sleep)', en: '5. Deep Sleep' },
    description: { 
      ja: '寝付きが悪い時や、眠りが浅い時に。ブラウンノイズとデルタ波の低い周波数で脳を休息モードへ切り替えます。', 
      en: 'For restless nights. Brown noise and Delta waves to shift the brain and body into rest mode.' 
    },
    noiseType: 'brown',
    beatBand: 'delta',
    baseFrequency: 174
  }
];

export const evidenceCards: EvidenceCard[] = [
  { 
    key: 'noise-colors', 
    title: { ja: 'ノイズ色の違い', en: 'Differences between noise colors' }, 
    summary: { ja: '白・ピンク・ブラウン・ブルー・ヴァイオレットは、周波数ごとの強さが違う音です。', en: 'White, pink, brown, blue, and violet noise differ by frequency weighting.' }, 
    strength: 'Strong', 
    caveat: { ja: '個人差があります。', en: 'User experience varies a lot.' }, 
    links: [{ label: 'Pink noise review', url: 'https://pubmed.ncbi.nlm.nih.gov/34964434/' }] 
  },
  { 
    key: 'binaural-beats', 
    title: { ja: 'ビートについて', en: 'About Beats' }, 
    summary: { ja: '左右の耳に少し違う周波数を出して、差分のうなりを知覚させます。', en: 'Two nearby tones are sent separately to each ear so the listener perceives a beat.' }, 
    strength: 'Mixed', 
    caveat: { ja: '医療的な効果を断定しません。', en: 'No medical claims are made.' }, 
    links: [{ label: 'Systematic review', url: 'https://pubmed.ncbi.nlm.nih.gov/37205669/' }] 
  }
];

const platformNotes: LocalizedList = {
  ja: ['iOS はブラウザの制限が強く、バックグラウンド再生は OS の状態に左右されます。', 'Android は PWA と Media Session が比較的素直に動きます。'],
  en: ['iOS has stricter browser limits.', 'Android usually handles PWA and Media Session well.']
};

export function getPlatformNotes(locale: Locale): string[] {
  return resolveLocalizedList(platformNotes, locale);
}

export const timerOptions = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60] as const;

export function getNoiseLabel(locale: Locale, key: NoiseType): string {
  const item = noiseTypes.find((noiseType) => noiseType.key === key);
  return item ? resolveLocalizedText(item.label, locale) : key;
}